@extends('layouts.app')

@section('title', $tool->name.' | Prazzu Tools')
@section('meta_description', $tool->description)
@section('canonical_url', route($tool->routeName))

@section('content')
<x-tools.page :title="$tool->name" :description="$tool->description" :icon="$tool->icon" :slug="$tool->slug"><x-tools.form-panel title="Premissas mensais"><form method="POST" action="{{route('tools.comparador-clt-pj-autonomo.calculate')}}" class="row g-3">@csrf
<div class="col-12"><h3 class="h5">CLT</h3></div><div class="col-md-3"><x-tools.form.money name="clt_gross" label="Salário bruto" :value="old('clt_gross')" required/></div><div class="col-md-3"><x-tools.form.money name="clt_benefits" label="Benefícios líquidos" :value="old('clt_benefits','0,00')" required/></div><div class="col-md-3"><x-tools.form.input name="clt_employee_deductions" label="Descontos estimados" type="number" step="0.000001" suffix="%" :value="old('clt_employee_deductions','10')" required/></div><div class="col-md-3"><x-tools.form.input name="clt_company_burden" label="Encargos/provisões empresa" type="number" step="0.000001" suffix="%" :value="old('clt_company_burden','40')" required/></div>
<div class="col-12"><h3 class="h5">PJ</h3></div><div class="col-md-4"><x-tools.form.money name="pj_invoice" label="Nota fiscal" :value="old('pj_invoice')" required/></div><div class="col-md-4"><x-tools.form.input name="pj_taxes" label="Tributos PJ" type="number" step="0.000001" suffix="%" :value="old('pj_taxes','6')" required/></div><div class="col-md-4"><x-tools.form.money name="pj_expenses" label="Despesas da PJ" :value="old('pj_expenses','0,00')" required/></div>
<div class="col-12"><h3 class="h5">Autônomo</h3></div><div class="col-md-4"><x-tools.form.money name="autonomous_gross" label="Remuneração bruta" :value="old('autonomous_gross')" required/></div><div class="col-md-4"><x-tools.form.input name="autonomous_deductions" label="INSS/IRRF estimados" type="number" step="0.000001" suffix="%" :value="old('autonomous_deductions','20')" required/></div><div class="col-md-4"><x-tools.form.input name="autonomous_company_burden" label="Encargo da empresa" type="number" step="0.000001" suffix="%" :value="old('autonomous_company_burden','20')" required/></div>
<div class="col-12"><button class="btn btn-primary">Comparar modelos</button></div></form></x-tools.form-panel>
@isset($result)
    <span data-analytics-result="main" hidden></span><x-tools.result-panel title="Comparação"><div class="row g-3">@foreach($result->summary as $item)<div class="col-md-6"><x-tools.result-metric :label="$item->label" :value="$item->value" :description="$item->description"/></div>@endforeach</div><div class="table-responsive mt-4"><table class="table"><thead><tr><th>Modelo</th><th>Líquido</th><th>Custo empresa</th></tr></thead><tbody>@foreach($result->details['comparison'] as $model=>$row)<tr><th>{{$model}}</th><td>{{$row['net']}}</td><td>{{$row['company_cost']}}</td></tr>@endforeach</tbody></table></div><div class="alert alert-warning">Comparação financeira; não valida vínculo empregatício, pejotização ou incidências específicas.</div></x-tools.result-panel>@endisset</x-tools.page>
@endsection
