@extends('layouts.app')

@section('title', $tool->name.' | Prazzu Tools')
@section('meta_description', $tool->description)
@section('canonical_url', route($tool->routeName))

@section('content')
<x-tools.page :title="$tool->name" :description="$tool->description" :icon="$tool->icon" :slug="$tool->slug"><x-tools.form-panel title="Dados da declaração"><form method="POST" action="{{route('tools.declaracao-trabalho-renda.calculate')}}" class="row g-3">@csrf
@foreach(['name'=>'Trabalhador','document'=>'CPF/documento','employer'=>'Empregador/declarante','occupation'=>'Função','city'=>'Cidade'] as $n=>$l)<div class="col-md-4"><x-tools.form.input :name="$n" :label="$l" :value="old($n)" required/></div>@endforeach<div class="col-md-4"><x-tools.form.input name="start_date" label="Início do vínculo" type="date" :value="old('start_date')" required/></div><div class="col-md-4"><x-tools.form.money name="monthly_income" label="Renda mensal" :value="old('monthly_income')" required/></div><div class="col-md-4"><x-tools.form.input name="issue_date" label="Data de emissão" type="date" :value="old('issue_date',date('Y-m-d'))" required/></div><div class="col-12"><button class="btn btn-primary">Gerar declaração</button></div></form></x-tools.form-panel>
@isset($result)
    <span data-analytics-result="main" hidden></span>@php($d=$result->details['document'])<x-tools.result-panel title="Declaração pronta"><div class="card"><div class="card-body py-5"><h3 class="text-center mb-5">{{$d['title']}}</h3><p class="lh-lg">{{$d['text']}}</p><p class="text-end mt-5">{{$d['location']}}</p><div class="text-center mt-5 pt-4 border-top">{{$d['signer']}}<br><small>Assinatura do declarante</small></div></div></div><div class="alert alert-warning mt-4"><strong>Limitações:</strong> {{implode(' ', $d['notice']['limitations'])}}</div><div class="d-flex gap-2 mt-3"><form method="post" action="{{ route('tools.declaracao-trabalho-renda.export.pdf') }}">@csrf @foreach(old() as $key=>$value) @if(!is_array($value)&&$key!=='_token')<input type="hidden" name="{{ $key }}" value="{{ $value }}">@endif @endforeach<button class="btn btn-outline-primary">Baixar PDF</button></form><form method="post" action="{{ route('tools.declaracao-trabalho-renda.export.excel') }}">@csrf @foreach(old() as $key=>$value) @if(!is_array($value)&&$key!=='_token')<input type="hidden" name="{{ $key }}" value="{{ $value }}">@endif @endforeach<button class="btn btn-outline-success">Baixar Excel (.xlsx)</button></form></div></x-tools.result-panel>@endisset</x-tools.page>
@endsection
