<?php

return [
    [
        'slug' => 'gerador-de-contrato',
        'name' => 'Gerador de Contrato',
        'description' => 'Gere contratos de prestação de serviços contábeis personalizados.',
        'category' => 'geradores',
        'icon' => 'bi-file-earmark-text',
        'route_name' => 'tools.show',
        'version' => '0.0.0-placeholder',
        'access' => 'free',
        'status' => 'active',
        'position' => 10,
        'featured' => true,
        'keywords' => [
            'contrato',
            'prestação de serviços',
            'cliente',
        ],
    ],
    [
        'slug' => 'calculadora-de-impostos',
        'name' => 'Calculadora de Impostos',
        'description' => 'Calcule impostos e tributos de forma rápida e precisa.',
        'category' => 'calculadoras',
        'icon' => 'bi-calculator',
        'route_name' => 'tools.show',
        'version' => '0.0.0-placeholder',
        'access' => 'free',
        'status' => 'active',
        'position' => 20,
        'featured' => true,
        'keywords' => [
            'imposto',
            'tributo',
            'fiscal',
        ],
    ],
    [
        'slug' => 'validador-de-cnpj',
        'name' => 'Validador de CNPJ',
        'description' => 'Valide CNPJs e consulte informações básicas de empresas.',
        'category' => 'validadores',
        'icon' => 'bi-shield-check',
        'route_name' => 'tools.show',
        'version' => '0.0.0-placeholder',
        'access' => 'free',
        'status' => 'active',
        'position' => 30,
        'featured' => true,
        'keywords' => [
            'cnpj',
            'empresa',
            'validação',
        ],
    ],
    [
        'slug' => 'conversor-de-arquivos',
        'name' => 'Conversor de Arquivos',
        'description' => 'Converta arquivos entre diferentes formatos com facilidade.',
        'category' => 'conversores',
        'icon' => 'bi-arrow-left-right',
        'route_name' => 'tools.show',
        'version' => '0.0.0-placeholder',
        'access' => 'free',
        'status' => 'active',
        'position' => 40,
        'featured' => true,
        'keywords' => [
            'arquivo',
            'converter',
            'formato',
        ],
    ],
    [
        'slug' => 'gerador-de-procuracao',
        'name' => 'Gerador de Procuração',
        'description' => 'Gere procurações eletrônicas para seus clientes.',
        'category' => 'geradores',
        'icon' => 'bi-file-earmark-text',
        'route_name' => 'tools.show',
        'version' => '0.0.0-placeholder',
        'access' => 'free',
        'status' => 'active',
        'position' => 50,
        'featured' => true,
        'keywords' => [
            'procuração',
            'cliente',
            'documento',
        ],
    ],
    [
        'slug' => 'calculadora-de-rescisao',
        'name' => 'Calculadora de Rescisão',
        'description' => 'Calcule valores de rescisão trabalhista automaticamente.',
        'category' => 'calculadoras',
        'icon' => 'bi-briefcase',
        'route_name' => 'tools.show',
        'version' => '0.0.0-placeholder',
        'access' => 'free',
        'status' => 'active',
        'position' => 60,
        'featured' => true,
        'keywords' => [
            'rescisão',
            'trabalhista',
            'empregado',
        ],
    ],
    [
        'slug' => 'organizador-de-documentos',
        'name' => 'Organizador de Documentos',
        'description' => 'Organize e gerencie documentos dos seus clientes.',
        'category' => 'organizadores',
        'icon' => 'bi-folder',
        'route_name' => 'tools.show',
        'version' => '0.0.0-placeholder',
        'access' => 'free',
        'status' => 'active',
        'position' => 70,
        'featured' => true,
        'keywords' => [
            'documentos',
            'organização',
            'clientes',
        ],
    ],
    [
        'slug' => 'gerador-de-relatorios',
        'name' => 'Gerador de Relatórios',
        'description' => 'Crie relatórios contábeis profissionais em segundos.',
        'category' => 'geradores',
        'icon' => 'bi-file-earmark-bar-graph',
        'route_name' => 'tools.show',
        'version' => '0.0.0-placeholder',
        'access' => 'free',
        'status' => 'active',
        'position' => 80,
        'featured' => true,
        'keywords' => [
            'relatório',
            'contábil',
            'documento',
        ],
    ],
];
