@extends('layouts.app')
@section('title', 'Planejamento de férias')
@section('content')
<div class="container py-4"><div class="d-flex justify-content-between mb-4"><div><h1 class="h3">Planejamento de férias</h1><p class="text-body-secondary">Calcule até 50 colaboradores em uma única rodada.</p></div><a class="btn btn-outline-primary align-self-start" href="{{ route('tools.calculadora-ferias.index') }}">Cálculo individual</a></div>
<form method="post" action="{{ route('tools.calculadora-ferias.plan') }}">@csrf
<div id="employees" class="vstack gap-3"><div class="card employee-row"><div class="card-body row g-3"><div class="col-md-3"><label class="form-label">Nome</label><input class="form-control" name="employees[0][name]" required></div><div class="col-md-2"><label class="form-label">Salário</label><input class="form-control" type="number" step="0.01" name="employees[0][monthly_salary]" required></div><div class="col-md-3"><label class="form-label">Início aquisitivo</label><input class="form-control" type="date" name="employees[0][acquisition_start_date]" required></div><div class="col-md-3"><label class="form-label">Início das férias</label><input class="form-control" type="date" name="employees[0][vacation_start_date]" required></div><div class="col-md-1"><label class="form-label">Faltas</label><input class="form-control" type="number" min="0" name="employees[0][unjustified_absences]" value="0"></div></div></div></div>
<div class="d-flex gap-2 mt-3"><button type="button" id="add-employee" class="btn btn-outline-secondary">Adicionar colaborador</button><button class="btn btn-primary">Gerar planejamento</button></div></form>
@if(isset($plan))<div class="card mt-4"><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Colaborador</th><th>Início</th><th>Total</th><th>Prazo de pagamento</th></tr></thead><tbody>@foreach($plan as $row)<tr><td>{{ $row['name'] }}</td><td>{{ $row['input']['vacation_start_date'] }}</td><td>{{ $row['result']['summary'][4]['value'] ?? '—' }}</td><td>{{ $row['result']['details']['payment_deadline'] ?? '—' }}</td></tr>@endforeach</tbody></table></div></div>@endif
</div>
<script>document.getElementById('add-employee').addEventListener('click',()=>{const box=document.querySelector('.employee-row').cloneNode(true);const i=document.querySelectorAll('.employee-row').length;box.querySelectorAll('input').forEach(el=>{el.name=el.name.replace(/employees\[0\]/,`employees[${i}]`);if(el.type!=='number')el.value='';});document.getElementById('employees').appendChild(box);});</script>
@endsection
