<?php

declare(strict_types=1);

return [
    'schema_version' => '1.0.0',
    'status' => 'e2e_lot_1_foundation_complete',
    'source_inventory' => 'config/product_tools.php',
    'contract_document' => 'docs/quality/E2E-AUTOMATION-CONTRACT.md',
    'lot_report' => 'docs/quality/E2E-LOT-1-FOUNDATION-INVENTORY.md',
    'expected_tool_count' => 32,
    'runtime' => [
        'catalog_manifest' => 'storage/app/e2e/runtime/tool-catalog.json',
    ],
    'execution_profiles' => [
        'smoke' => ['required_scenarios' => ['page_load'], 'blocking' => true],
        'regression' => ['required_scenarios' => ['page_load', 'valid', 'invalid'], 'blocking' => true],
        'full' => ['required_scenarios' => ['page_load', 'valid', 'invalid', 'boundary', 'downloads', 'access'], 'blocking' => true],
        'exploratory' => ['required_scenarios' => ['generated_variations'], 'blocking' => false],
    ],
    'risk_priorities' => ['critical' => 1, 'high' => 2, 'moderate' => 3, 'low' => 4],
    'tools' => [
        [
            'id' => 1,
            'module' => 'EmployeeCostCalculator',
            'slug' => 'custo-funcionario-clt',
            'risk' => 'high',
            'risk_source' => 'risk_profile',
            'required_scenarios' => ['page_load', 'valid', 'invalid'],
            'surfaces' => ['form', 'result', 'downloads', 'history', 'upload', 'batch', 'secondary_actions'],
            'download_formats' => ['csv', 'json', 'pdf', 'xlsx'],
        ],
        [
            'id' => 2,
            'module' => 'FactorRSimulator',
            'slug' => 'simulador-fator-r',
            'risk' => 'high',
            'risk_source' => 'risk_profile',
            'required_scenarios' => ['page_load', 'valid', 'invalid'],
            'surfaces' => ['form', 'result', 'downloads', 'history'],
            'download_formats' => ['csv', 'json', 'pdf'],
        ],
        [
            'id' => 3,
            'module' => 'LateDasCalculator',
            'slug' => 'das-em-atraso',
            'risk' => 'high',
            'risk_source' => 'risk_profile',
            'required_scenarios' => ['page_load', 'valid', 'invalid'],
            'surfaces' => ['form', 'result', 'downloads', 'history'],
            'download_formats' => ['csv', 'json', 'pdf'],
        ],
        [
            'id' => 4,
            'module' => 'LaborChargesCalculator',
            'slug' => 'encargos-trabalhistas',
            'risk' => 'high',
            'risk_source' => 'risk_profile',
            'required_scenarios' => ['page_load', 'valid', 'invalid'],
            'surfaces' => ['form', 'result', 'downloads', 'history'],
            'download_formats' => ['csv', 'json', 'pdf'],
        ],
        [
            'id' => 5,
            'module' => 'EmploymentModelComparator',
            'slug' => 'comparador-clt-pj-autonomo',
            'risk' => 'high',
            'risk_source' => 'risk_profile',
            'required_scenarios' => ['page_load', 'valid', 'invalid'],
            'surfaces' => ['form', 'result', 'downloads', 'history'],
            'download_formats' => ['csv', 'json', 'pdf'],
        ],
        [
            'id' => 6,
            'module' => 'EmployerInssCalculator',
            'slug' => 'inss-patronal',
            'risk' => 'high',
            'risk_source' => 'risk_profile',
            'required_scenarios' => ['page_load', 'valid', 'invalid'],
            'surfaces' => ['form', 'result', 'downloads', 'history'],
            'download_formats' => ['csv', 'json', 'pdf'],
        ],
        [
            'id' => 7,
            'module' => 'WorkingCapitalCalculator',
            'slug' => 'capital-de-giro',
            'risk' => 'low',
            'risk_source' => 'risk_profile',
            'required_scenarios' => ['page_load', 'valid', 'invalid'],
            'surfaces' => ['form', 'result', 'downloads', 'history'],
            'download_formats' => ['csv', 'json', 'pdf'],
        ],
        [
            'id' => 8,
            'module' => 'CashFlowCalculator',
            'slug' => 'fluxo-de-caixa',
            'risk' => 'low',
            'risk_source' => 'risk_profile',
            'required_scenarios' => ['page_load', 'valid', 'invalid'],
            'surfaces' => ['form', 'result', 'downloads', 'history'],
            'download_formats' => ['csv', 'json', 'pdf'],
        ],
        [
            'id' => 9,
            'module' => 'BreakEvenCalculator',
            'slug' => 'ponto-de-equilibrio',
            'risk' => 'low',
            'risk_source' => 'risk_profile',
            'required_scenarios' => ['page_load', 'valid', 'invalid'],
            'surfaces' => ['form', 'result', 'downloads', 'history'],
            'download_formats' => ['csv', 'json', 'pdf'],
        ],
        [
            'id' => 10,
            'module' => 'MarginMarkupCalculator',
            'slug' => 'calculadora-margem-markup',
            'risk' => 'moderate',
            'risk_source' => 'e2e_inventory_assessment',
            'required_scenarios' => ['page_load', 'valid', 'invalid'],
            'surfaces' => ['form', 'result', 'downloads', 'history'],
            'download_formats' => ['csv', 'json', 'pdf'],
        ],
        [
            'id' => 11,
            'module' => 'ProLaboreSimulator',
            'slug' => 'simulador-pro-labore-ideal',
            'risk' => 'high',
            'risk_source' => 'e2e_inventory_assessment',
            'required_scenarios' => ['page_load', 'valid', 'invalid'],
            'surfaces' => ['form', 'result', 'downloads', 'history'],
            'download_formats' => ['csv', 'json', 'pdf'],
        ],
        [
            'id' => 12,
            'module' => 'SalesCommissionCalculator',
            'slug' => 'comissao-vendedores',
            'risk' => 'moderate',
            'risk_source' => 'risk_profile',
            'required_scenarios' => ['page_load', 'valid', 'invalid'],
            'surfaces' => ['form', 'result', 'downloads', 'history'],
            'download_formats' => ['csv', 'json', 'pdf'],
        ],
        [
            'id' => 13,
            'module' => 'PayslipGenerator',
            'slug' => 'gerador-holerite',
            'risk' => 'high',
            'risk_source' => 'risk_profile',
            'required_scenarios' => ['page_load', 'valid', 'invalid'],
            'surfaces' => ['form', 'result', 'downloads', 'history', 'document_generation'],
            'download_formats' => ['json', 'pdf'],
        ],
        [
            'id' => 14,
            'module' => 'AdmissionSimulator',
            'slug' => 'simulador-admissao',
            'risk' => 'high',
            'risk_source' => 'risk_profile',
            'required_scenarios' => ['page_load', 'valid', 'invalid'],
            'surfaces' => ['form', 'result', 'downloads', 'history'],
            'download_formats' => ['json', 'pdf'],
        ],
        [
            'id' => 15,
            'module' => 'LaborTerminationCalculator',
            'slug' => 'calculadora-de-rescisao',
            'risk' => 'critical',
            'risk_source' => 'e2e_inventory_assessment',
            'required_scenarios' => ['page_load', 'valid', 'invalid'],
            'surfaces' => ['form', 'result', 'downloads', 'history'],
            'download_formats' => ['csv', 'json', 'pdf'],
        ],
        [
            'id' => 16,
            'module' => 'SalaryAdjustmentCalculator',
            'slug' => 'reajuste-salarial',
            'risk' => 'high',
            'risk_source' => 'risk_profile',
            'required_scenarios' => ['page_load', 'valid', 'invalid'],
            'surfaces' => ['form', 'result', 'downloads', 'history'],
            'download_formats' => ['csv', 'json', 'pdf'],
        ],
        [
            'id' => 17,
            'module' => 'ProfitDistributionCalculator',
            'slug' => 'distribuicao-de-lucros',
            'risk' => 'high',
            'risk_source' => 'e2e_inventory_assessment',
            'required_scenarios' => ['page_load', 'valid', 'invalid'],
            'surfaces' => ['form', 'result', 'downloads', 'history'],
            'download_formats' => ['csv', 'json', 'pdf'],
        ],
        [
            'id' => 18,
            'module' => 'IncomeStatementGenerator',
            'slug' => 'declaracao-rendimentos',
            'risk' => 'high',
            'risk_source' => 'risk_profile',
            'required_scenarios' => ['page_load', 'valid', 'invalid'],
            'surfaces' => ['form', 'result', 'downloads', 'history', 'document_generation'],
            'download_formats' => ['json', 'pdf'],
        ],
        [
            'id' => 19,
            'module' => 'WorkIncomeStatementGenerator',
            'slug' => 'declaracao-trabalho-renda',
            'risk' => 'moderate',
            'risk_source' => 'risk_profile',
            'required_scenarios' => ['page_load', 'valid', 'invalid'],
            'surfaces' => ['form', 'result', 'downloads', 'history', 'document_generation'],
            'download_formats' => ['json', 'pdf'],
        ],
        [
            'id' => 20,
            'module' => 'TaxRegimeComparator',
            'slug' => 'comparador-tributario',
            'risk' => 'high',
            'risk_source' => 'risk_profile',
            'required_scenarios' => ['page_load', 'valid', 'invalid'],
            'surfaces' => ['form', 'result', 'downloads', 'history'],
            'download_formats' => ['csv', 'json', 'pdf', 'xlsx'],
        ],
        [
            'id' => 21,
            'module' => 'NetSalaryCalculator',
            'slug' => 'calculadora-salario-liquido',
            'risk' => 'high',
            'risk_source' => 'risk_profile',
            'required_scenarios' => ['page_load', 'valid', 'invalid'],
            'surfaces' => ['form', 'result', 'downloads', 'history'],
            'download_formats' => ['csv', 'json', 'pdf', 'xlsx'],
        ],
        [
            'id' => 22,
            'module' => 'OvertimeCalculator',
            'slug' => 'calculadora-hora-extra',
            'risk' => 'high',
            'risk_source' => 'risk_profile',
            'required_scenarios' => ['page_load', 'valid', 'invalid'],
            'surfaces' => ['form', 'result', 'downloads'],
            'download_formats' => ['csv', 'json', 'pdf', 'xlsx'],
        ],
        [
            'id' => 23,
            'module' => 'DifalIcmsCalculator',
            'slug' => 'calculadora-difal-icms',
            'risk' => 'critical',
            'risk_source' => 'risk_profile',
            'required_scenarios' => ['page_load', 'valid', 'invalid'],
            'surfaces' => ['form', 'result', 'downloads'],
            'download_formats' => ['csv', 'json', 'pdf', 'xlsx'],
        ],
        [
            'id' => 24,
            'module' => 'ProLaboreProfitDistributionCalculator',
            'slug' => 'calculadora-pro-labore-distribuicao-lucros',
            'risk' => 'critical',
            'risk_source' => 'risk_profile',
            'required_scenarios' => ['page_load', 'valid', 'invalid'],
            'surfaces' => ['form', 'result', 'downloads', 'history', 'secondary_actions'],
            'download_formats' => ['csv', 'json', 'pdf', 'xlsx'],
        ],
        [
            'id' => 25,
            'module' => 'AccountingFeesCalculator',
            'slug' => 'calculadora-de-honorarios-contabeis',
            'risk' => 'moderate',
            'risk_source' => 'e2e_inventory_assessment',
            'required_scenarios' => ['page_load', 'valid', 'invalid'],
            'surfaces' => ['form', 'result', 'downloads', 'history'],
            'download_formats' => ['csv', 'json', 'pdf', 'xlsx'],
        ],
        [
            'id' => 26,
            'module' => 'BusinessDocumentValidator',
            'slug' => 'validador-de-cnpj',
            'risk' => 'high',
            'risk_source' => 'e2e_inventory_assessment',
            'required_scenarios' => ['page_load', 'valid', 'invalid'],
            'surfaces' => ['form', 'result', 'downloads', 'history', 'upload'],
            'download_formats' => ['csv', 'json', 'pdf', 'xlsx'],
        ],
        [
            'id' => 27,
            'module' => 'ContractGenerator',
            'slug' => 'gerador-de-contratos',
            'risk' => 'high',
            'risk_source' => 'risk_profile',
            'required_scenarios' => ['page_load', 'valid', 'invalid'],
            'surfaces' => ['form', 'result', 'downloads', 'history', 'document_generation', 'secondary_actions'],
            'download_formats' => ['docx', 'json', 'pdf'],
        ],
        [
            'id' => 28,
            'module' => 'FederalPaymentGuideGenerator',
            'slug' => 'gerador-darf-gps',
            'risk' => 'critical',
            'risk_source' => 'risk_profile',
            'required_scenarios' => ['page_load', 'valid', 'invalid'],
            'surfaces' => ['form', 'result', 'downloads', 'history', 'document_generation', 'secondary_actions'],
            'download_formats' => ['csv', 'json', 'pdf', 'xlsx'],
        ],
        [
            'id' => 29,
            'module' => 'FiscalXmlConverter',
            'slug' => 'conversor-fiscal-xml',
            'risk' => 'high',
            'risk_source' => 'risk_profile',
            'required_scenarios' => ['page_load', 'valid', 'invalid'],
            'surfaces' => ['form', 'result', 'downloads', 'history', 'upload', 'batch', 'secondary_actions'],
            'download_formats' => ['csv', 'json', 'pdf', 'xlsx'],
        ],
        [
            'id' => 30,
            'module' => 'ReceiptIssuer',
            'slug' => 'emissor-de-recibos',
            'risk' => 'moderate',
            'risk_source' => 'risk_profile',
            'required_scenarios' => ['page_load', 'valid', 'invalid'],
            'surfaces' => ['form', 'result', 'downloads', 'history', 'upload', 'batch', 'document_generation', 'secondary_actions'],
            'download_formats' => ['json', 'pdf', 'xlsx'],
        ],
        [
            'id' => 31,
            'module' => 'SimplesNacionalCalculator',
            'slug' => 'calculadora-simples-nacional',
            'risk' => 'critical',
            'risk_source' => 'e2e_inventory_assessment',
            'required_scenarios' => ['page_load', 'valid', 'invalid'],
            'surfaces' => ['form', 'result', 'downloads', 'history'],
            'download_formats' => ['csv', 'json', 'pdf', 'xlsx'],
        ],
        [
            'id' => 32,
            'module' => 'VacationCalculator',
            'slug' => 'calculadora-ferias',
            'risk' => 'high',
            'risk_source' => 'risk_profile',
            'required_scenarios' => ['page_load', 'valid', 'invalid'],
            'surfaces' => ['form', 'result', 'downloads', 'history', 'secondary_actions'],
            'download_formats' => ['csv', 'json', 'pdf', 'xlsx'],
        ],
    ],
];
