<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Governança de recursos Prazzu Plus
    |--------------------------------------------------------------------------
    |
    | `legacy_debt` congela exatamente os recursos Plus existentes antes do
    | saneamento de monetização. O gate arquitetural não permite acrescentar
    | um novo recurso Plus sem implementação, autorização central e testes.
    | À medida que um recurso for corrigido nos próximos lotes, remova sua
    | entrada desta lista para que ele passe a cumprir o contrato estrito.
    |
    */
    'generic_keys' => [
        'advanced_productivity',
        'advanced_analysis',
    ],

    // Snapshot final de proteção contra regressão auditado no Prazzu Plus Lote 8.
    'catalog_tool_count' => 50,
    'declared_plus_feature_count' => 144,
    'legacy_debt_ceiling' => 0,
    'strict_contract_floor' => 144,

    // Snapshots criptográficos impedem trocar contratos silenciosamente sem
    // alterar as contagens consolidadas. As listas são ordenadas antes do hash.
    'declared_contracts_checksum' => 'd3584e3826fa8b696c5256d8962162592e2b103ac5fbebcb4fdb23583c134f2d',
    'legacy_debt_checksum' => 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',

    /*
    |--------------------------------------------------------------------------
    | Certificação funcional
    |--------------------------------------------------------------------------
    |
    | Contrato estrito comprova estrutura, gate e teste de acesso. Certificação
    | funcional é uma camada adicional: exige teste comportamental marcado com
    | CoversPlusFeature. Após a remediação, os 137 contratos estão certificados
    | e sua composição exata também fica protegida por checksum.
    |
    */
    'functional_contracts' => [
        'simulador-ecad-direitos-autorais:period_projection',
        'calculadora-lucro-real:tax_base_diagnostics',
        'simulador-reforma-tributaria-consumo:transition_diagnostics',
        'calculadora-icms-proprio:inside_calculation',
        'consultor-validador-cfop:catalog_details',
        'validador-fiscal-sefaz:key_breakdown',
        'analisador-certificado-digital-a1:technical_report',
        'calculadora-de-honorarios-contabeis:commercial_proposal',
        'calculadora-de-honorarios-contabeis:history',
        'calculadora-de-honorarios-contabeis:history_export',
        'calculadora-de-honorarios-contabeis:service_contract',
        'calculadora-de-rescisao:historical_report',
        'calculadora-de-rescisao:history',
        'calculadora-de-rescisao:repeat_history',
        'calculadora-das-retroativo-regularizacao-simples:regularization',
        'calculadora-depreciacao-ativos:portfolio_projection',
        'calculadora-difal-icms:double_base',
        'calculadora-difal-icms:export',
        'calculadora-difal-icms:fcp',
        'calculadora-difal-icms:interstate_assist',
        'calculadora-ferias:multiple_employees',
        'calculadora-hora-extra:dsr',
        'calculadora-hora-extra:export',
        'calculadora-hora-extra:night',
        'calculadora-hora-extra:reflexes',
        'calculadora-icms-st:history',
        'calculadora-irpj-csll-lucro-presumido:history',
        'calculadora-iss:monthly_consolidation',
        'calculadora-margem-markup:batch_processing',
        'calculadora-margem-markup:export',
        'calculadora-margem-markup:history',
        'calculadora-margem-markup:scenarios',
        'calculadora-parcelamento-tributario:balance_evolution',
        'calculadora-parcelamento-tributario:report',
        'calculadora-pis-cofins:history',
        'calculadora-pis-cofins:memory',
        'calculadora-pro-labore-distribuicao-lucros:history_exports',
        'calculadora-pro-labore-distribuicao-lucros:scenario_planning',
        'calculadora-retencoes-nota-fiscal:history',
        'calculadora-retencoes-nota-fiscal:memory',
        'calculadora-retencoes-nota-fiscal:report',
        'calculadora-salario-liquido:custom_discounts',
        'calculadora-salario-liquido:export',
        'calculadora-salario-liquido:history',
        'calculadora-salario-liquido:variable_earnings',
        'calculadora-simples-nacional:alerts',
        'calculadora-simples-nacional:annual_projection',
        'calculadora-simples-nacional:compare_annexes',
        'calculadora-simples-nacional:compare_scenarios',
        'calculadora-simples-nacional:monthly_history',
        'calculadora-turnover:segmented_analysis',
        'capital-de-giro:projections',
        'comissao-vendedores:batch_sellers',
        'comparador-clt-pj-autonomo:spreadsheet_export',
        'comparador-tributario:annual_projection',
        'comparador-tributario:multiple_scenarios',
        'conversor-fiscal-xml:document_comparison',
        'custo-funcionario-clt:branded_report',
        'custo-funcionario-clt:projections',
        'das-em-atraso:spreadsheet_export',
        'declaracao-rendimentos:spreadsheet_export',
        'declaracao-trabalho-renda:spreadsheet_export',
        'distribuicao-de-lucros:partners',
        'emissor-de-recibos:custom_branding',
        'encargos-trabalhistas:spreadsheet_export',
        'fluxo-de-caixa:cash_flow_scenarios',
        'gerador-darf-gps:favorites',
        'gerador-de-contratos:company_autofill',
        'gerador-de-contratos:contract_library',
        'gerador-de-contratos:favorites',
        'gerador-de-contratos:history',
        'gerador-de-contratos:smart_clauses',
        'gerador-de-contratos:version_comparison',
        'gerador-holerite:spreadsheet_export',
        'inss-patronal:spreadsheet_export',
        'ponto-de-equilibrio:scenario_comparison',
        'reajuste-salarial:spreadsheet_export',
        'simulador-admissao:spreadsheet_export',
        'simulador-distribuicao-lucros-balanco:planning',
        'simulador-fator-r:spreadsheet_export',
        'simulador-mei-microempresa:annual_projection',
        'simulador-mei-microempresa:business_costs',
        'simulador-mei-microempresa:migration_point',
        'simulador-pro-labore-ideal:scenarios',
        'validador-de-cnpj:batch_export',
        'validador-de-cnpj:batch_processing',
        'validador-de-cnpj:history',
        'comparador-tributario:export',
        'comparador-tributario:history',
        'comparador-tributario:professional_report',
        'conversor-fiscal-xml:batch_processing',
        'conversor-fiscal-xml:history',
        'conversor-fiscal-xml:professional_export',
        'emissor-de-recibos:batch_generation',
        'emissor-de-recibos:history',
        'emissor-de-recibos:saved_profiles',
        'gerador-darf-gps:history',
        'gerador-darf-gps:professional_export',
        'simulador-distribuicao-lucros-balanco:report',
        'simulador-mei-microempresa:report',
        'custo-funcionario-clt:batch_processing',
        'custo-funcionario-clt:company_profiles',
        'custo-funcionario-clt:csv_export',
        'custo-funcionario-clt:csv_import',
        'custo-funcionario-clt:employee_profiles',
        'custo-funcionario-clt:employment_model_comparison',
        'custo-funcionario-clt:history',
        'custo-funcionario-clt:professional_report',
        'custo-funcionario-clt:scenarios',
        'custo-funcionario-clt:xlsx_export',
        'custo-funcionario-clt:xlsx_import',
        'calculadora-icms-st:adjusted_mva',
        'calculadora-icms-st:export',
        'calculadora-icms-st:fcp',
        'calculadora-icms-st:interstate',
        'calculadora-icms-st:multiple_items',
        'calculadora-irpj-csll-lucro-presumido:carry_forward_limit',
        'calculadora-irpj-csll-lucro-presumido:credits',
        'calculadora-irpj-csll-lucro-presumido:export',
        'calculadora-irpj-csll-lucro-presumido:multiple_activities',
        'calculadora-irpj-csll-lucro-presumido:periodicity',
        'calculadora-irpj-csll-lucro-presumido:scenario_comparison',
        'calculadora-pis-cofins:aggregate_credits',
        'calculadora-pis-cofins:comparison',
        'calculadora-pis-cofins:credit_breakdown',
        'calculadora-pis-cofins:export',
        'calculadora-pis-cofins:multiple_operations',
        'calculadora-das-retroativo-regularizacao-simples:multiple_competencies',
        'calculadora-das-retroativo-regularizacao-simples:report',
        'calculadora-depreciacao-ativos:export',
        'calculadora-depreciacao-ativos:methods',
        'calculadora-depreciacao-ativos:multiple_assets',
        'calculadora-ferias:history',
        'calculadora-ferias:professional_export',
        'calculadora-ferias:vacation_planning',
        'calculadora-iss:export',
        'calculadora-iss:multiple_services',
        'calculadora-iss:municipality_scenarios',
        'calculadora-iss:retention',
        'calculadora-parcelamento-tributario:export',
        'calculadora-parcelamento-tributario:scenario_comparison',
        'calculadora-retencoes-nota-fiscal:custom_rules',
        'calculadora-retencoes-nota-fiscal:export',
        'calculadora-retencoes-nota-fiscal:multiple_notes',
    ],
    'functional_contract_floor' => 144,
    'functional_debt_ceiling' => 0,
    'functional_contracts_checksum' => 'd3584e3826fa8b696c5256d8962162592e2b103ac5fbebcb4fdb23583c134f2d',

    // Snapshot exato dos contratos estruturais saneados até o Lote 7.
    // Nenhum deles pode desaparecer, voltar ao legado ou ser trocado silenciosamente.
    'strict_contracts' => [
        'simulador-ecad-direitos-autorais:period_projection',
        'calculadora-lucro-real:tax_base_diagnostics',
        'simulador-reforma-tributaria-consumo:transition_diagnostics',
        'calculadora-icms-proprio:inside_calculation',
        'consultor-validador-cfop:catalog_details',
        'validador-fiscal-sefaz:key_breakdown',
        'analisador-certificado-digital-a1:technical_report',
        'calculadora-de-honorarios-contabeis:commercial_proposal',
        'calculadora-de-honorarios-contabeis:history',
        'calculadora-de-honorarios-contabeis:history_export',
        'calculadora-de-honorarios-contabeis:service_contract',
        'calculadora-de-rescisao:historical_report',
        'calculadora-de-rescisao:history',
        'calculadora-de-rescisao:repeat_history',
        'calculadora-das-retroativo-regularizacao-simples:regularization',
        'calculadora-depreciacao-ativos:portfolio_projection',
        'calculadora-difal-icms:double_base',
        'calculadora-difal-icms:export',
        'calculadora-difal-icms:fcp',
        'calculadora-difal-icms:interstate_assist',
        'calculadora-ferias:multiple_employees',
        'calculadora-hora-extra:dsr',
        'calculadora-hora-extra:export',
        'calculadora-hora-extra:night',
        'calculadora-hora-extra:reflexes',
        'calculadora-icms-st:history',
        'calculadora-irpj-csll-lucro-presumido:history',
        'calculadora-iss:monthly_consolidation',
        'calculadora-margem-markup:batch_processing',
        'calculadora-margem-markup:export',
        'calculadora-margem-markup:history',
        'calculadora-margem-markup:scenarios',
        'calculadora-parcelamento-tributario:balance_evolution',
        'calculadora-parcelamento-tributario:report',
        'calculadora-pis-cofins:history',
        'calculadora-pis-cofins:memory',
        'calculadora-pro-labore-distribuicao-lucros:history_exports',
        'calculadora-pro-labore-distribuicao-lucros:scenario_planning',
        'calculadora-retencoes-nota-fiscal:history',
        'calculadora-retencoes-nota-fiscal:memory',
        'calculadora-retencoes-nota-fiscal:report',
        'calculadora-salario-liquido:custom_discounts',
        'calculadora-salario-liquido:export',
        'calculadora-salario-liquido:history',
        'calculadora-salario-liquido:variable_earnings',
        'calculadora-simples-nacional:alerts',
        'calculadora-simples-nacional:annual_projection',
        'calculadora-simples-nacional:compare_annexes',
        'calculadora-simples-nacional:compare_scenarios',
        'calculadora-simples-nacional:monthly_history',
        'calculadora-turnover:segmented_analysis',
        'capital-de-giro:projections',
        'comissao-vendedores:batch_sellers',
        'comparador-clt-pj-autonomo:spreadsheet_export',
        'comparador-tributario:annual_projection',
        'comparador-tributario:multiple_scenarios',
        'conversor-fiscal-xml:document_comparison',
        'custo-funcionario-clt:branded_report',
        'custo-funcionario-clt:projections',
        'das-em-atraso:spreadsheet_export',
        'declaracao-rendimentos:spreadsheet_export',
        'declaracao-trabalho-renda:spreadsheet_export',
        'distribuicao-de-lucros:partners',
        'emissor-de-recibos:custom_branding',
        'encargos-trabalhistas:spreadsheet_export',
        'fluxo-de-caixa:cash_flow_scenarios',
        'gerador-darf-gps:favorites',
        'gerador-de-contratos:company_autofill',
        'gerador-de-contratos:contract_library',
        'gerador-de-contratos:favorites',
        'gerador-de-contratos:history',
        'gerador-de-contratos:smart_clauses',
        'gerador-de-contratos:version_comparison',
        'gerador-holerite:spreadsheet_export',
        'inss-patronal:spreadsheet_export',
        'ponto-de-equilibrio:scenario_comparison',
        'reajuste-salarial:spreadsheet_export',
        'simulador-admissao:spreadsheet_export',
        'simulador-distribuicao-lucros-balanco:planning',
        'simulador-fator-r:spreadsheet_export',
        'simulador-mei-microempresa:annual_projection',
        'simulador-mei-microempresa:business_costs',
        'simulador-mei-microempresa:migration_point',
        'simulador-pro-labore-ideal:scenarios',
        'validador-de-cnpj:batch_export',
        'validador-de-cnpj:batch_processing',
        'validador-de-cnpj:history',
        'comparador-tributario:export',
        'comparador-tributario:history',
        'comparador-tributario:professional_report',
        'conversor-fiscal-xml:batch_processing',
        'conversor-fiscal-xml:history',
        'conversor-fiscal-xml:professional_export',
        'emissor-de-recibos:batch_generation',
        'emissor-de-recibos:history',
        'emissor-de-recibos:saved_profiles',
        'gerador-darf-gps:history',
        'gerador-darf-gps:professional_export',
        'simulador-distribuicao-lucros-balanco:report',
        'simulador-mei-microempresa:report',
        'custo-funcionario-clt:batch_processing',
        'custo-funcionario-clt:company_profiles',
        'custo-funcionario-clt:csv_export',
        'custo-funcionario-clt:csv_import',
        'custo-funcionario-clt:employee_profiles',
        'custo-funcionario-clt:employment_model_comparison',
        'custo-funcionario-clt:history',
        'custo-funcionario-clt:professional_report',
        'custo-funcionario-clt:scenarios',
        'custo-funcionario-clt:xlsx_export',
        'custo-funcionario-clt:xlsx_import',
        'calculadora-icms-st:adjusted_mva',
        'calculadora-icms-st:export',
        'calculadora-icms-st:fcp',
        'calculadora-icms-st:interstate',
        'calculadora-icms-st:multiple_items',
        'calculadora-irpj-csll-lucro-presumido:carry_forward_limit',
        'calculadora-irpj-csll-lucro-presumido:credits',
        'calculadora-irpj-csll-lucro-presumido:export',
        'calculadora-irpj-csll-lucro-presumido:multiple_activities',
        'calculadora-irpj-csll-lucro-presumido:periodicity',
        'calculadora-irpj-csll-lucro-presumido:scenario_comparison',
        'calculadora-pis-cofins:aggregate_credits',
        'calculadora-pis-cofins:comparison',
        'calculadora-pis-cofins:credit_breakdown',
        'calculadora-pis-cofins:export',
        'calculadora-pis-cofins:multiple_operations',
        'calculadora-das-retroativo-regularizacao-simples:multiple_competencies',
        'calculadora-das-retroativo-regularizacao-simples:report',
        'calculadora-depreciacao-ativos:export',
        'calculadora-depreciacao-ativos:methods',
        'calculadora-depreciacao-ativos:multiple_assets',
        'calculadora-ferias:history',
        'calculadora-ferias:professional_export',
        'calculadora-ferias:vacation_planning',
        'calculadora-iss:export',
        'calculadora-iss:multiple_services',
        'calculadora-iss:municipality_scenarios',
        'calculadora-iss:retention',
        'calculadora-parcelamento-tributario:export',
        'calculadora-parcelamento-tributario:scenario_comparison',
        'calculadora-retencoes-nota-fiscal:custom_rules',
        'calculadora-retencoes-nota-fiscal:export',
        'calculadora-retencoes-nota-fiscal:multiple_notes',
    ],

    'legacy_debt' => [],
];
