<?php

declare(strict_types=1);

return [
    'schema_version' => '3.13.0',
    'release_readiness' => 'accounting_expansion_fiscal_trio_2026',
    'source' => 'README.md',
    'continuity_log' => 'docs/IMPLEMENTATION-LOTS.md',
    'inventory_document' => 'docs/PRODUCT-TOOLS-INVENTORY.md',
    'expected_module_count' => 43,

    'official' => [
        ['id' => 1, 'key' => 'employee-cost', 'name' => 'Calculadora de Custo de Funcionário CLT', 'slug' => 'custo-funcionario-clt', 'module' => 'EmployeeCostCalculator', 'state' => 'implemented', 'vertical' => 'contabilidade', 'release_order' => 10],
        ['id' => 2, 'key' => 'factor-r', 'name' => 'Simulador de Fator R', 'slug' => 'simulador-fator-r', 'module' => 'FactorRSimulator', 'state' => 'implemented', 'vertical' => 'contabilidade', 'release_order' => 20],
        ['id' => 3, 'key' => 'late-das', 'name' => 'Calculadora de DAS em Atraso', 'slug' => 'das-em-atraso', 'module' => 'LateDasCalculator', 'state' => 'implemented', 'vertical' => 'contabilidade', 'release_order' => 21],
        ['id' => 4, 'key' => 'labor-charges', 'name' => 'Calculadora de Encargos Trabalhistas', 'slug' => 'encargos-trabalhistas', 'module' => 'LaborChargesCalculator', 'state' => 'implemented', 'vertical' => 'contabilidade', 'release_order' => 11],
        ['id' => 5, 'key' => 'employment-model', 'name' => 'Simulador CLT × PJ × Autônomo', 'slug' => 'comparador-clt-pj-autonomo', 'module' => 'EmploymentModelComparator', 'state' => 'implemented', 'vertical' => 'contabilidade', 'release_order' => 13],
        ['id' => 6, 'key' => 'employer-inss', 'name' => 'Calculadora de INSS Patronal', 'slug' => 'inss-patronal', 'module' => 'EmployerInssCalculator', 'state' => 'implemented', 'vertical' => 'contabilidade', 'release_order' => 12],
        ['id' => 7, 'key' => 'working-capital', 'name' => 'Calculadora de Capital de Giro', 'slug' => 'capital-de-giro', 'module' => 'WorkingCapitalCalculator', 'state' => 'implemented', 'vertical' => 'contabilidade', 'release_order' => 23],
        ['id' => 8, 'key' => 'cash-flow', 'name' => 'Calculadora de Fluxo de Caixa', 'slug' => 'fluxo-de-caixa', 'module' => 'CashFlowCalculator', 'state' => 'implemented', 'vertical' => 'contabilidade', 'release_order' => 24],
        ['id' => 9, 'key' => 'break-even', 'name' => 'Calculadora de Ponto de Equilíbrio', 'slug' => 'ponto-de-equilibrio', 'module' => 'BreakEvenCalculator', 'state' => 'implemented', 'vertical' => 'contabilidade', 'release_order' => 25],
        ['id' => 10, 'key' => 'product-pricing', 'name' => 'Calculadora de Precificação de Produtos', 'slug' => 'calculadora-margem-markup', 'module' => 'MarginMarkupCalculator', 'state' => 'implemented', 'vertical' => 'contabilidade', 'release_order' => 26],
        ['id' => 11, 'key' => 'pro-labore', 'name' => 'Simulador de Pró-Labore Ideal', 'slug' => 'simulador-pro-labore-ideal', 'module' => 'ProLaboreSimulator', 'state' => 'implemented', 'vertical' => 'contabilidade', 'release_order' => 14],
        ['id' => 12, 'key' => 'sales-commission', 'name' => 'Calculadora de Comissão de Vendedores', 'slug' => 'comissao-vendedores', 'module' => 'SalesCommissionCalculator', 'state' => 'implemented', 'vertical' => 'contabilidade', 'release_order' => 27],
        ['id' => 13, 'key' => 'payslip', 'name' => 'Gerador de Holerite', 'slug' => 'gerador-holerite', 'module' => 'PayslipGenerator', 'state' => 'implemented', 'vertical' => 'contabilidade', 'release_order' => 16],
        ['id' => 14, 'key' => 'admission', 'name' => 'Simulador de Admissão', 'slug' => 'simulador-admissao', 'module' => 'AdmissionSimulator', 'state' => 'implemented', 'vertical' => 'contabilidade', 'release_order' => 17],
        ['id' => 15, 'key' => 'termination', 'name' => 'Simulador de Demissão', 'slug' => 'calculadora-de-rescisao', 'module' => 'LaborTerminationCalculator', 'state' => 'implemented', 'vertical' => 'contabilidade', 'release_order' => 18],
        ['id' => 16, 'key' => 'salary-adjustment', 'name' => 'Calculadora de Reajuste Salarial', 'slug' => 'reajuste-salarial', 'module' => 'SalaryAdjustmentCalculator', 'state' => 'implemented', 'vertical' => 'contabilidade', 'release_order' => 19],
        ['id' => 17, 'key' => 'profit-distribution', 'name' => 'Calculadora de Distribuição de Lucros', 'slug' => 'distribuicao-de-lucros', 'module' => 'ProfitDistributionCalculator', 'state' => 'implemented', 'vertical' => 'contabilidade', 'release_order' => 15],
        ['id' => 18, 'key' => 'income-statement', 'name' => 'Gerador de Declaração de Rendimentos', 'slug' => 'declaracao-rendimentos', 'module' => 'IncomeStatementGenerator', 'state' => 'implemented', 'vertical' => 'contabilidade', 'release_order' => 28],
        ['id' => 19, 'key' => 'work-income-statement', 'name' => 'Gerador de Declaração de Trabalho/Renda', 'slug' => 'declaracao-trabalho-renda', 'module' => 'WorkIncomeStatementGenerator', 'state' => 'implemented', 'vertical' => 'contabilidade', 'release_order' => 29],
        ['id' => 20, 'key' => 'tax-regime', 'name' => 'Simulador Tributário (Simples × Lucro Presumido × Lucro Real)', 'slug' => 'comparador-tributario', 'module' => 'TaxRegimeComparator', 'state' => 'implemented', 'vertical' => 'contabilidade', 'release_order' => 22],
        ['id' => 21, 'key' => 'net-salary', 'name' => 'Calculadora de Salário Líquido', 'slug' => 'calculadora-salario-liquido', 'module' => 'NetSalaryCalculator', 'state' => 'implemented', 'vertical' => 'contabilidade', 'release_order' => 30],
        ['id' => 22, 'key' => 'overtime', 'name' => 'Calculadora de Hora Extra, Adicional Noturno e DSR', 'slug' => 'calculadora-hora-extra', 'module' => 'OvertimeCalculator', 'state' => 'implemented', 'vertical' => 'contabilidade', 'release_order' => 31],
        ['id' => 23, 'key' => 'difal-icms', 'name' => 'Calculadora DIFAL / ICMS Interestadual + FCP', 'slug' => 'calculadora-difal-icms', 'module' => 'DifalIcmsCalculator', 'state' => 'implemented', 'vertical' => 'contabilidade', 'release_order' => 32],
        ['id' => 24, 'key' => 'partner-withdrawal-planner', 'name' => 'Planejador de Retirada de Sócios', 'slug' => 'calculadora-pro-labore-distribuicao-lucros', 'module' => 'ProLaboreProfitDistributionCalculator', 'state' => 'implemented', 'vertical' => 'contabilidade', 'release_order' => 1],
        ['id' => 25, 'key' => 'accounting-fees', 'name' => 'Calculadora de Honorários Contábeis', 'slug' => 'calculadora-de-honorarios-contabeis', 'module' => 'AccountingFeesCalculator', 'state' => 'implemented', 'vertical' => 'contabilidade', 'release_order' => 2],
        ['id' => 26, 'key' => 'business-document-validator', 'name' => 'Validador Inteligente de CNPJ, CPF e IE', 'slug' => 'validador-de-cnpj', 'module' => 'BusinessDocumentValidator', 'state' => 'implemented', 'vertical' => 'contabilidade', 'release_order' => 3],
        ['id' => 27, 'key' => 'contract-generator', 'name' => 'Gerador de Contratos', 'slug' => 'gerador-de-contratos', 'module' => 'ContractGenerator', 'state' => 'implemented', 'vertical' => 'contabilidade', 'release_order' => 4],
        ['id' => 28, 'key' => 'federal-payment-guide', 'name' => 'Gerador Inteligente de DARF/GPS', 'slug' => 'gerador-darf-gps', 'module' => 'FederalPaymentGuideGenerator', 'state' => 'implemented', 'vertical' => 'contabilidade', 'release_order' => 5],
        ['id' => 29, 'key' => 'fiscal-xml-converter', 'name' => 'Conversor Fiscal de XML', 'slug' => 'conversor-fiscal-xml', 'module' => 'FiscalXmlConverter', 'state' => 'implemented', 'vertical' => 'contabilidade', 'release_order' => 6],
        ['id' => 30, 'key' => 'receipt-issuer', 'name' => 'Emissor de Recibos', 'slug' => 'emissor-de-recibos', 'module' => 'ReceiptIssuer', 'state' => 'implemented', 'vertical' => 'contabilidade', 'release_order' => 7],
        ['id' => 31, 'key' => 'simples-nacional', 'name' => 'Calculadora de Simples Nacional', 'slug' => 'calculadora-simples-nacional', 'module' => 'SimplesNacionalCalculator', 'state' => 'implemented', 'vertical' => 'contabilidade', 'release_order' => 8],
        ['id' => 32, 'key' => 'vacation', 'name' => 'Calculadora de Férias', 'slug' => 'calculadora-ferias', 'module' => 'VacationCalculator', 'state' => 'implemented', 'vertical' => 'contabilidade', 'release_order' => 9],
        ['id' => 33, 'key' => 'turnover', 'name' => 'Calculadora de Turnover', 'slug' => 'calculadora-turnover', 'module' => 'TurnoverCalculator', 'state' => 'implemented', 'vertical' => 'rh', 'release_order' => 33],
        ['id' => 34, 'key' => 'presumed-profit-irpj-csll', 'name' => 'Calculadora de IRPJ e CSLL — Lucro Presumido', 'slug' => 'calculadora-irpj-csll-lucro-presumido', 'module' => 'PresumedProfitIrpjCsllCalculator', 'state' => 'implemented', 'vertical' => 'contabilidade', 'release_order' => 34],
        ['id' => 35, 'key' => 'pis-cofins', 'name' => 'Calculadora PIS e COFINS', 'slug' => 'calculadora-pis-cofins', 'module' => 'PisCofinsCalculator', 'state' => 'implemented', 'vertical' => 'contabilidade', 'release_order' => 35],
        ['id' => 36, 'key' => 'icms-st', 'name' => 'Calculadora de ICMS-ST', 'slug' => 'calculadora-icms-st', 'module' => 'IcmsStCalculator', 'state' => 'implemented', 'vertical' => 'contabilidade', 'release_order' => 36],
        ['id' => 37, 'key' => 'invoice-withholding', 'name' => 'Calculadora de Retenções na Nota Fiscal', 'slug' => 'calculadora-retencoes-nota-fiscal', 'module' => 'InvoiceWithholdingCalculator', 'state' => 'implemented', 'vertical' => 'contabilidade', 'release_order' => 37],
        ['id' => 38, 'key' => 'asset-depreciation', 'name' => 'Calculadora de Depreciação de Ativos', 'slug' => 'calculadora-depreciacao-ativos', 'module' => 'AssetDepreciationCalculator', 'state' => 'implemented', 'vertical' => 'contabilidade', 'release_order' => 38],
        ['id' => 39, 'key' => 'tax-installment', 'name' => 'Calculadora de Parcelamento Tributário', 'slug' => 'calculadora-parcelamento-tributario', 'module' => 'TaxInstallmentCalculator', 'state' => 'implemented', 'vertical' => 'contabilidade', 'release_order' => 39],
        ['id' => 40, 'key' => 'mei-to-microenterprise', 'name' => 'Simulador MEI → Microempresa', 'slug' => 'simulador-mei-microempresa', 'module' => 'MeiToMicroenterpriseSimulator', 'state' => 'implemented', 'vertical' => 'contabilidade', 'release_order' => 40],
        ['id' => 41, 'key' => 'iss', 'name' => 'Calculadora de ISS', 'slug' => 'calculadora-iss', 'module' => 'IssCalculator', 'state' => 'implemented', 'vertical' => 'contabilidade', 'release_order' => 41],
        ['id' => 42, 'key' => 'profit-distribution-balance-comparison', 'name' => 'Simulador de Distribuição de Lucros com Balanço × sem Balanço', 'slug' => 'simulador-distribuicao-lucros-balanco', 'module' => 'ProfitDistributionBalanceSimulator', 'state' => 'implemented', 'vertical' => 'contabilidade', 'release_order' => 42],
        ['id' => 43, 'key' => 'retroactive-das-regularization', 'name' => 'Calculadora de DAS Retroativo + Regularização do Simples', 'slug' => 'calculadora-das-retroativo-regularizacao-simples', 'module' => 'RetroactiveDasRegularizationCalculator', 'state' => 'implemented', 'vertical' => 'contabilidade', 'release_order' => 43],
    ],

    'functional_overlap_reviews' => [
        [
            'module' => 'ProfitDistributionBalanceSimulator',
            'classification' => 'resolved_distinct_balance_comparison_scope',
            'state' => 'resolved',
            'related_modules' => ['ProfitDistributionCalculator'],
            'distinction' => 'A calculadora histórica apura distribuição societária de um lucro contábil; o novo simulador compara explicitamente um cenário com balanço contra uma referência parametrizada sem balanço e projeta os dois cenários.',
        ],
        [
            'module' => 'RetroactiveDasRegularizationCalculator',
            'classification' => 'resolved_distinct_reconstitution_scope',
            'state' => 'resolved',
            'related_modules' => ['LateDasCalculator'],
            'distinction' => 'DAS em Atraso parte de um principal já conhecido; DAS Retroativo reconstitui o principal estimado pelo faturamento e alíquota informada, consolida competências e planeja regularização financeira.',
        ],
        [
            'module' => 'ProLaboreProfitDistributionCalculator',
            'classification' => 'resolved_distinct_planning_scope',
            'state' => 'resolved',
            'related_modules' => ['ProLaboreSimulator', 'ProfitDistributionCalculator'],
            'distinction' => 'Os módulos especializados calculam cada domínio isoladamente; este módulo consolida a composição da retirada, o total líquido do sócio, o custo empresarial e o lucro remanescente em cenários comparáveis.',
        ],
    ],
];
