<?php

return [
    'modules' => [
        // App\Tools\CnpjValidator\CnpjValidatorTool::class,
    ],

    'categories' => [
        'geradores' => ['name' => 'Geradores', 'icon' => 'bi-magic'],
        'calculadoras' => ['name' => 'Calculadoras', 'icon' => 'bi-calculator'],
        'conversores' => ['name' => 'Conversores', 'icon' => 'bi-arrow-left-right'],
        'validadores' => ['name' => 'Validadores', 'icon' => 'bi-shield-check'],
        'organizadores' => ['name' => 'Organizadores', 'icon' => 'bi-calendar2-week'],
        'documentos' => ['name' => 'Documentos', 'icon' => 'bi-file-earmark-text'],
        'fiscal' => ['name' => 'Fiscal e tributário', 'icon' => 'bi-receipt'],
        'trabalhista' => ['name' => 'Trabalhista', 'icon' => 'bi-people'],
        'societario' => ['name' => 'Societário', 'icon' => 'bi-buildings'],
        'outros' => ['name' => 'Outros', 'icon' => 'bi-three-dots'],
    ],

    /*
    | Ferramentas provisórias do catálogo.
    | Quando um módulo real registrar o mesmo slug, sua definição substitui
    | automaticamente esta entrada sem alterar a home ou os controllers.
    */
    'catalog' => [
        [
            'slug' => 'gerador-de-contrato',
            'name' => 'Gerador de Contrato',
            'description' => 'Gere contratos de prestação de serviços contábeis personalizados.',
            'category' => 'geradores',
            'icon' => 'bi-file-earmark-text',
            'tone' => 'pink',
            'badge' => 'Popular',
            'badge_tone' => 'purple',
            'is_free' => true,
            'is_premium' => false,
            'is_featured' => true,
            'is_popular' => true,
            'is_active' => true,
            'uses_count' => 12500,
            'uses_label' => '12.5k usos',
            'position' => 10,
            'keywords' => ['contrato', 'prestação de serviços', 'cliente'],
        ],
        [
            'slug' => 'calculadora-de-impostos',
            'name' => 'Calculadora de Impostos',
            'description' => 'Calcule impostos e tributos de forma rápida e precisa.',
            'category' => 'calculadoras',
            'icon' => 'bi-calculator',
            'tone' => 'purple',
            'badge' => 'Popular',
            'badge_tone' => 'purple',
            'is_free' => true,
            'is_premium' => false,
            'is_featured' => true,
            'is_popular' => true,
            'is_active' => true,
            'uses_count' => 8700,
            'uses_label' => '8.7k usos',
            'position' => 20,
            'keywords' => ['imposto', 'tributo', 'fiscal'],
        ],
        [
            'slug' => 'validador-de-cnpj',
            'name' => 'Validador de CNPJ',
            'description' => 'Valide CNPJs e consulte informações básicas de empresas.',
            'category' => 'validadores',
            'icon' => 'bi-shield-check',
            'tone' => 'green',
            'badge' => 'Popular',
            'badge_tone' => 'purple',
            'is_free' => true,
            'is_premium' => false,
            'is_featured' => true,
            'is_popular' => true,
            'is_active' => true,
            'uses_count' => 6300,
            'uses_label' => '6.3k usos',
            'position' => 30,
            'keywords' => ['cnpj', 'empresa', 'validação'],
        ],
        [
            'slug' => 'conversor-de-arquivos',
            'name' => 'Conversor de Arquivos',
            'description' => 'Converta arquivos entre diferentes formatos com facilidade.',
            'category' => 'conversores',
            'icon' => 'bi-arrow-left-right',
            'tone' => 'purple',
            'badge' => 'Popular',
            'badge_tone' => 'purple',
            'is_free' => true,
            'is_premium' => false,
            'is_featured' => true,
            'is_popular' => false,
            'is_active' => true,
            'uses_count' => 0,
            'uses_label' => null,
            'position' => 40,
            'keywords' => ['arquivo', 'converter', 'formato'],
        ],
        [
            'slug' => 'gerador-de-procuracao',
            'name' => 'Gerador de Procuração',
            'description' => 'Gere procurações eletrônicas para seus clientes.',
            'category' => 'geradores',
            'icon' => 'bi-file-earmark-text',
            'tone' => 'blue',
            'badge' => 'Novo',
            'badge_tone' => 'green',
            'is_free' => true,
            'is_premium' => false,
            'is_featured' => true,
            'is_popular' => true,
            'is_active' => true,
            'uses_count' => 4200,
            'uses_label' => '4.2k usos',
            'position' => 50,
            'keywords' => ['procuração', 'cliente', 'documento'],
        ],
        [
            'slug' => 'calculadora-de-rescisao',
            'name' => 'Calculadora de Rescisão',
            'description' => 'Calcule valores de rescisão trabalhista automaticamente.',
            'category' => 'calculadoras',
            'icon' => 'bi-briefcase',
            'tone' => 'pink',
            'badge' => 'Novo',
            'badge_tone' => 'green',
            'is_free' => true,
            'is_premium' => false,
            'is_featured' => true,
            'is_popular' => true,
            'is_active' => true,
            'uses_count' => 3800,
            'uses_label' => '3.8k usos',
            'position' => 60,
            'keywords' => ['rescisão', 'trabalhista', 'empregado'],
        ],
        [
            'slug' => 'organizador-de-documentos',
            'name' => 'Organizador de Documentos',
            'description' => 'Organize e gerencie documentos dos seus clientes.',
            'category' => 'organizadores',
            'icon' => 'bi-folder',
            'tone' => 'purple',
            'badge' => 'Novo',
            'badge_tone' => 'green',
            'is_free' => true,
            'is_premium' => false,
            'is_featured' => true,
            'is_popular' => false,
            'is_active' => true,
            'uses_count' => 0,
            'uses_label' => null,
            'position' => 70,
            'keywords' => ['documentos', 'organização', 'clientes'],
        ],
        [
            'slug' => 'gerador-de-relatorios',
            'name' => 'Gerador de Relatórios',
            'description' => 'Crie relatórios contábeis profissionais em segundos.',
            'category' => 'geradores',
            'icon' => 'bi-file-earmark-bar-graph',
            'tone' => 'purple',
            'badge' => 'Novo',
            'badge_tone' => 'green',
            'is_free' => true,
            'is_premium' => false,
            'is_featured' => true,
            'is_popular' => false,
            'is_active' => true,
            'uses_count' => 0,
            'uses_label' => null,
            'position' => 80,
            'keywords' => ['relatório', 'contábil', 'documento'],
        ],
    ],
];
