@extends('layouts.admin')

@section('title', 'Campanhas inteligentes')

@section('content')
<div class="container-fluid py-4">
    <div class="d-flex flex-column flex-lg-row justify-content-between gap-3 mb-4">
        <div><h1 class="h3 mb-1">Campanhas inteligentes</h1><p class="text-body-secondary mb-0">Contextos, palavras-chave, ferramentas e conversões atribuídas.</p></div>
        <form method="GET" class="d-flex gap-2 align-items-end"><div><label class="form-label small">Período</label><select name="period" class="form-select" onchange="this.form.submit()">@foreach(['1'=>'Hoje','7'=>'7 dias','30'=>'30 dias','90'=>'90 dias'] as $value=>$label)<option value="{{ $value }}" @selected($selected_period === $value)>{{ $label }}</option>@endforeach</select></div></form>
    </div>

    <div class="d-flex flex-wrap gap-2 mb-4"><a class="badge text-bg-light border text-decoration-none" href="{{ route('admin.analytics.acquisition') }}">Aquisição geral</a><span class="badge text-bg-primary">Campanhas inteligentes</span></div>

    <div class="row g-3 mb-4">@foreach([
        ['Sessões',$summary['sessions']],['Visitantes',$summary['visitors']],['Contextos',$summary['contexts']],['Campanhas',$summary['campaigns']],['Palavras-chave',$summary['keywords']],['Conversões',$summary['conversions']],['Taxa',number_format($summary['conversion_rate'],1,',','.').'%']
    ] as [$label,$value])<div class="col-6 col-lg"><div class="card border-0 shadow-sm h-100"><div class="card-body"><div class="small text-body-secondary">{{ $label }}</div><div class="h4 mb-0 mt-2">{{ $value }}</div></div></div></div>@endforeach</div>

    @foreach([['Performance de campanhas',$campaigns],['Ranking de palavras-chave',$keywords],['Conversão por contexto',$contexts]] as [$title,$rows])
    <div class="card border-0 shadow-sm mb-4"><div class="card-header bg-transparent fw-semibold">{{ $title }}</div><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Identificação</th><th class="text-end">Sessões</th><th class="text-end">Visitantes</th><th class="text-end">Cliques</th><th class="text-end">Inícios</th><th class="text-end">Conclusões</th><th class="text-end">Contas</th><th class="text-end">Assinaturas</th><th class="text-end">Conversão</th></tr></thead><tbody>
    @forelse($rows as $row)<tr><td class="fw-semibold">{{ $row->label }}</td><td class="text-end">{{ $row->sessions }}</td><td class="text-end">{{ $row->visitors }}</td><td class="text-end">{{ $row->tool_clicks }}</td><td class="text-end">{{ $row->calculations_started }}</td><td class="text-end">{{ $row->calculations_completed }}</td><td class="text-end">{{ $row->accounts }}</td><td class="text-end">{{ $row->subscriptions }}</td><td class="text-end"><strong>{{ number_format($row->conversion_rate,1,',','.') }}%</strong></td></tr>@empty<tr><td colspan="9" class="text-center text-body-secondary py-4">Sem dados no período.</td></tr>@endforelse
    </tbody></table></div></div>@endforeach

    <div class="card border-0 shadow-sm mb-4"><div class="card-header bg-transparent fw-semibold">Ferramentas descobertas pelas campanhas</div><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Ferramenta</th><th class="text-end">Cliques</th><th class="text-end">Visitantes</th><th class="text-end">Cálculos iniciados</th><th class="text-end">Cálculos concluídos</th></tr></thead><tbody>@forelse($tools as $tool)<tr><td class="fw-semibold">{{ $tool->tool }}</td><td class="text-end">{{ $tool->clicks }}</td><td class="text-end">{{ $tool->visitors }}</td><td class="text-end">{{ $tool->calculations_started }}</td><td class="text-end">{{ $tool->calculations_completed }}</td></tr>@empty<tr><td colspan="5" class="text-center text-body-secondary py-4">Nenhum clique registrado.</td></tr>@endforelse</tbody></table></div></div>

    <div class="row g-3 mb-4">
        <div class="col-xl-7"><div class="card border-0 shadow-sm h-100"><div class="card-header bg-transparent fw-semibold">Comparação com o período anterior</div><div class="card-body"><div class="row g-3">@foreach([['Sessões','sessions'],['Visitantes','visitors'],['Conversões','conversions'],['Taxa de conversão','conversion_rate']] as [$label,$metric])@php($delta=$comparison[$metric])<div class="col-6 col-lg-3"><div class="border rounded p-3 h-100"><div class="small text-body-secondary">{{ $label }}</div><div class="h5 mb-0 {{ $delta > 0 ? 'text-success' : ($delta < 0 ? 'text-danger' : '') }}">{{ $delta > 0 ? '+' : '' }}{{ number_format($delta,1,',','.') }}%</div></div></div>@endforeach</div><div class="small text-body-secondary mt-3">Período anterior: {{ $previous['period']->label() }}</div></div></div></div>
        <div class="col-xl-5"><div class="card border-0 shadow-sm h-100"><div class="card-header bg-transparent fw-semibold">Insights automáticos</div><div class="card-body">@forelse($campaign_insights as $insight)<div class="border-start border-4 border-{{ $insight->severity }} ps-3 mb-3"><div class="fw-semibold">{{ $insight->title }}</div><div class="small">{{ $insight->message }}</div><div class="small text-body-secondary mt-1">{{ $insight->recommendation }}</div></div>@empty<p class="text-body-secondary mb-0">Ainda não há volume suficiente para gerar recomendações confiáveis.</p>@endforelse</div></div></div>
    </div>

    <div class="card border-0 shadow-sm mb-4"><div class="card-header bg-transparent fw-semibold">Performance por origem</div><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Origem</th><th class="text-end">Sessões</th><th class="text-end">Cliques</th><th class="text-end">Conclusões</th><th class="text-end">Contas</th><th class="text-end">Assinaturas</th><th class="text-end">Conversão</th></tr></thead><tbody>@forelse($origins as $row)<tr><td class="fw-semibold">{{ $row->label }}</td><td class="text-end">{{ $row->sessions }}</td><td class="text-end">{{ $row->tool_clicks }}</td><td class="text-end">{{ $row->calculations_completed }}</td><td class="text-end">{{ $row->accounts }}</td><td class="text-end">{{ $row->subscriptions }}</td><td class="text-end"><strong>{{ number_format($row->conversion_rate,1,',','.') }}%</strong></td></tr>@empty<tr><td colspan="7" class="text-center text-body-secondary py-4">Sem dados de origem.</td></tr>@endforelse</tbody></table></div></div>

    <div class="row g-3 mb-4">
        <div class="col-xl-6"><div class="card border-0 shadow-sm h-100"><div class="card-header bg-transparent fw-semibold">Performance de CTAs</div><div class="table-responsive"><table class="table mb-0"><thead><tr><th>CTA</th><th class="text-end">Exibições</th><th class="text-end">Cliques</th><th class="text-end">CTR</th></tr></thead><tbody>@forelse($ctas as $cta)<tr><td>{{ $cta->label }}</td><td class="text-end">{{ $cta->views }}</td><td class="text-end">{{ $cta->clicks }}</td><td class="text-end">{{ number_format($cta->ctr,1,',','.') }}%</td></tr>@empty<tr><td colspan="4" class="text-center text-body-secondary py-4">Sem dados de CTA.</td></tr>@endforelse</tbody></table></div></div></div>
        <div class="col-xl-6"><div class="card border-0 shadow-sm h-100"><div class="card-header bg-transparent fw-semibold">Jornada entre ferramentas</div><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Sequência</th><th class="text-end">Transições</th></tr></thead><tbody>@forelse($journeys as $journey)<tr><td>{{ $journey->journey }}</td><td class="text-end">{{ $journey->transitions }}</td></tr>@empty<tr><td colspan="2" class="text-center text-body-secondary py-4">Ainda não há jornadas com duas ferramentas.</td></tr>@endforelse</tbody></table></div></div></div>
    </div>

    <div class="row g-3 mb-4">
        <div class="col-xl-7"><div class="card border-0 shadow-sm h-100"><div class="card-header bg-transparent fw-semibold">Retorno e custo por campanha</div><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Campanha</th><th class="text-end">Custo estimado</th><th class="text-end">Receita rastreada</th><th class="text-end">CPA assinatura</th><th class="text-end">ROAS</th><th class="text-end">ROI</th></tr></thead><tbody>@forelse($roi as $row)<tr><td class="fw-semibold">{{ $row->campaign }}</td><td class="text-end">{{ $row->cost_cents > 0 ? 'R$ '.number_format($row->cost_cents / 100, 2, ',', '.') : '—' }}</td><td class="text-end">{{ $row->revenue_cents > 0 ? 'R$ '.number_format($row->revenue_cents / 100, 2, ',', '.') : '—' }}</td><td class="text-end">{{ $row->cost_per_subscription_cents !== null ? 'R$ '.number_format($row->cost_per_subscription_cents / 100, 2, ',', '.') : '—' }}</td><td class="text-end">{{ $row->roas !== null ? number_format($row->roas, 2, ',', '.').'x' : '—' }}</td><td class="text-end {{ $row->roi !== null && $row->roi >= 0 ? 'text-success' : ($row->roi !== null ? 'text-danger' : '') }}">{{ $row->roi !== null ? number_format($row->roi, 1, ',', '.').'%' : '—' }}</td></tr>@empty<tr><td colspan="6" class="text-center text-body-secondary py-4">Sem campanhas atribuídas no período.</td></tr>@endforelse</tbody></table></div><div class="card-footer small text-body-secondary">O custo é proporcional ao investimento mensal cadastrado. A receita depende dos valores enviados nos eventos de assinatura.</div></div></div>
        <div class="col-xl-5"><div class="card border-0 shadow-sm h-100"><div class="card-header bg-transparent fw-semibold">Retenção por contexto</div><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Palavra-chave</th><th class="text-end">Coorte</th><th class="text-end">7 dias</th><th class="text-end">30 dias</th></tr></thead><tbody>@forelse($retention as $row)<tr><td class="fw-semibold">{{ $row->label }}</td><td class="text-end">{{ $row->cohort }}</td><td class="text-end">{{ $row->retention_7d !== null ? number_format($row->retention_7d,1,',','.').'%' : 'Aguardando' }}</td><td class="text-end">{{ $row->retention_30d !== null ? number_format($row->retention_30d,1,',','.').'%' : 'Aguardando' }}</td></tr>@empty<tr><td colspan="4" class="text-center text-body-secondary py-4">Sem coortes atribuídas.</td></tr>@endforelse</tbody></table></div><div class="card-footer small text-body-secondary">A retenção considera uma nova sessão no mesmo contexto dentro da janela indicada.</div></div></div>
    </div>

    <div class="card border-0 shadow-sm"><div class="card-header bg-transparent fw-semibold">Funil por campanha</div><div class="card-body"><div class="accordion" id="campaignFunnels">@forelse($funnels as $funnel)<div class="accordion-item"><h2 class="accordion-header"><button class="accordion-button {{ $loop->first ? '' : 'collapsed' }}" data-bs-toggle="collapse" data-bs-target="#campaign-funnel-{{ $loop->index }}"><strong>{{ $funnel['campaign'] }}</strong></button></h2><div id="campaign-funnel-{{ $loop->index }}" class="accordion-collapse collapse {{ $loop->first ? 'show' : '' }}" data-bs-parent="#campaignFunnels"><div class="accordion-body"><div class="row g-3">@foreach($funnel['steps'] as $step)<div class="col-sm-6 col-xl"><div class="border rounded p-3 h-100"><div class="small text-body-secondary">{{ $step['label'] }}</div><div class="h4">{{ $step['visitors'] }}</div><div class="progress"><div class="progress-bar" style="width: {{ min(100,$step['step_rate']) }}%">{{ number_format($step['step_rate'],1,',','.') }}%</div></div></div></div>@endforeach</div></div></div></div>@empty<p class="text-center text-body-secondary">Sem dados suficientes.</p>@endforelse</div></div></div>
</div>
@endsection
