@extends('layouts.app')
@section('title', 'Insights Inteligentes | Analytics | Prazzu Tools')
@section('content')
<div class="container-fluid py-4">
 <div class="d-flex flex-column flex-xl-row justify-content-between gap-3 mb-4">
  <div><div class="d-flex flex-wrap gap-2 mb-2"><span class="badge text-bg-warning">Analytics 2.0</span><a class="badge text-bg-light border text-decoration-none" href="{{ route('admin.analytics.index') }}">Dashboard</a><a class="badge text-bg-light border text-decoration-none" href="{{ route('admin.analytics.funnels') }}">Funis</a></div><h1 class="h2 mb-1">Insights inteligentes</h1><p class="text-body-secondary mb-0">Alertas, tendências, oportunidades e recomendações geradas a partir dos eventos auditáveis.</p></div>
  <form method="post" action="{{ route('admin.analytics.insights.generate', request()->query()) }}">@csrf<button class="btn btn-primary"><i class="bi bi-arrow-repeat me-1"></i>Analisar agora</button></form>
 </div>
 @if(session('status'))<div class="alert alert-success">{{ session('status') }}</div>@endif
 <form method="get" class="card border-0 shadow-sm mb-4"><div class="card-body"><div class="row g-2 align-items-end">
  <div class="col-md-3"><label class="form-label">Período</label><select name="period" class="form-select">@foreach(['today'=>'Hoje','yesterday'=>'Ontem','7'=>'7 dias','30'=>'30 dias','90'=>'90 dias'] as $v=>$l)<option value="{{ $v }}" @selected($selected_period===$v)>{{ $l }}</option>@endforeach</select></div>
  <div class="col-md-3"><label class="form-label">Tipo</label><select name="type" class="form-select"><option value="">Todos</option>@foreach(['alert'=>'Alertas','trend'=>'Tendências','opportunity'=>'Oportunidades','recommendation'=>'Recomendações'] as $v=>$l)<option value="{{ $v }}" @selected($selected_type===$v)>{{ $l }}</option>@endforeach</select></div>
  <div class="col-md-3"><label class="form-label">Severidade</label><select name="severity" class="form-select"><option value="">Todas</option>@foreach(['danger'=>'Crítica','warning'=>'Atenção','info'=>'Informativa','success'=>'Positiva'] as $v=>$l)<option value="{{ $v }}" @selected($selected_severity===$v)>{{ $l }}</option>@endforeach</select></div>
  <div class="col-md-3"><button class="btn btn-outline-primary w-100">Aplicar filtros</button></div>
 </div></div></form>
 <div class="row g-3 mb-4">@foreach([['Total',$summary['total'],'bi-lightbulb'],['Alertas',$summary['alerts'],'bi-exclamation-triangle'],['Oportunidades',$summary['opportunities'],'bi-graph-up-arrow'],['Recomendações',$summary['recommendations'],'bi-check2-circle']] as [$l,$v,$i])<div class="col-6 col-xl-3"><div class="card border-0 shadow-sm h-100"><div class="card-body"><i class="bi {{ $i }} text-primary"></i><div class="small text-body-secondary mt-2">{{ $l }}</div><div class="h3 mb-0">{{ $v }}</div></div></div></div>@endforeach</div>
 <div class="row g-3">@forelse($insights as $insight)@php($color=['danger'=>'danger','warning'=>'warning','info'=>'info','success'=>'success'][$insight->severity] ?? 'secondary')<div class="col-xl-6"><div class="card border-{{ $color }} shadow-sm h-100"><div class="card-body"><div class="d-flex justify-content-between gap-2 mb-2"><div><span class="badge text-bg-{{ $color }}">{{ ucfirst($insight->type) }}</span> <span class="badge text-bg-light border">{{ $insight->status }}</span></div>@if($insight->change_percent !== null)<strong class="text-{{ $insight->change_percent < 0 ? 'danger' : 'success' }}">{{ number_format($insight->change_percent,1,',','.') }}%</strong>@endif</div><h2 class="h5">{{ $insight->title }}</h2><p>{{ $insight->message }}</p>@if($insight->recommendation)<div class="alert alert-light border mb-3"><strong>Próxima ação:</strong> {{ $insight->recommendation }}</div>@endif<form method="post" action="{{ route('admin.analytics.insights.status',$insight) }}" class="d-flex gap-2">@csrf @method('PATCH')<select name="status" class="form-select form-select-sm"><option value="open">Aberto</option><option value="acknowledged">Em análise</option><option value="resolved">Resolvido</option></select><button class="btn btn-sm btn-outline-secondary">Atualizar</button></form></div></div></div>@empty<div class="col-12"><div class="alert alert-light border text-center py-5">Nenhum insight relevante foi encontrado para este período.</div></div>@endforelse</div>
</div>
@endsection
