@extends('layouts.app')
@section('title','SEO Analytics | Prazzu Tools')
@section('content')
<div class="container-fluid py-4">
<div class="d-flex flex-column flex-lg-row justify-content-between gap-3 mb-4"><div><div class="d-flex flex-wrap gap-2 mb-2"><span class="badge text-bg-primary">Analytics 2.0</span><a class="badge text-bg-light border text-decoration-none" href="{{ route('admin.analytics.index') }}">Dashboard executivo</a><a class="badge text-bg-light border text-decoration-none" href="{{ route('admin.blog.analytics') }}">Blog</a></div><h1 class="h2 mb-1">SEO Analytics</h1><p class="text-body-secondary mb-0">Auditoria técnica, desempenho orgânico, Discover, News e resultados enriquecidos.</p></div></div>
    @include('admin.analytics.partials.page-guide', ['page' => 'seo'])
<form method="get" class="card border-0 shadow-sm mb-4"><div class="card-body"><div class="row g-2 align-items-end"><div class="col-sm-auto"><label class="form-label small">Período</label><select class="form-select" name="period" data-period-select>@foreach(['today'=>'Hoje','yesterday'=>'Ontem','7'=>'7 dias','30'=>'30 dias','90'=>'90 dias','custom'=>'Personalizado'] as $value=>$label)<option value="{{ $value }}" @selected($selected_period===$value)>{{ $label }}</option>@endforeach</select></div><div class="col-sm-auto {{ $selected_period==='custom'?'':'d-none' }}" data-custom-period><label class="form-label small">De</label><input class="form-control" type="date" name="start" value="{{ request('start',$period->start->toDateString()) }}"></div><div class="col-sm-auto {{ $selected_period==='custom'?'':'d-none' }}" data-custom-period><label class="form-label small">Até</label><input class="form-control" type="date" name="end" value="{{ request('end',$period->end->toDateString()) }}"></div><div class="col-sm-auto"><button class="btn btn-primary">Aplicar</button></div></div></div></form>
<div class="row g-3 mb-4">@foreach([['Artigos',$summary->posts],['Indexáveis',$summary->indexable],['Score médio',number_format($summary->average_score,1,',','.').'%'],['Críticos',$summary->critical],['Cliques',$summary->clicks],['Impressões',$summary->impressions],['CTR',number_format($summary->ctr,2,',','.').'%'],['Posição média',$summary->average_position ? number_format($summary->average_position,2,',','.') : '—'],['Discover',$summary->discover_clicks],['Google News',$summary->news_clicks],['Rich Results',$summary->rich_result_clicks]] as [$label,$value])<div class="col-6 col-lg-3 col-xxl-2"><div class="card border-0 shadow-sm h-100"><div class="card-body"><div class="small text-body-secondary">{{ $label }}</div><div class="h4 mb-0">{{ is_numeric($value)?number_format($value,0,',','.'):$value }}</div></div></div></div>@endforeach</div>
<div class="card border-0 shadow-sm mb-4"><div class="card-header bg-transparent fw-semibold">Desempenho por artigo</div><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Artigo</th><th>Auditoria</th><th class="text-end">Cliques</th><th class="text-end">Impressões</th><th class="text-end">CTR</th><th class="text-end">Posição</th><th></th></tr></thead><tbody>@forelse($posts as $row)<tr><td><div class="fw-semibold">{{ $row->post->title }}</div><small class="text-body-secondary">{{ $row->post->category }} · {{ $row->word_count }} palavras</small></td><td><span class="badge text-bg-{{ $row->audit_status }}">{{ $row->score }}%</span>@if($row->errors)<span class="small text-danger ms-1">{{ $row->errors }} críticos</span>@endif</td><td class="text-end">{{ number_format($row->clicks,0,',','.') }}</td><td class="text-end">{{ number_format($row->impressions,0,',','.') }}</td><td class="text-end">{{ number_format($row->ctr,2,',','.') }}%</td><td class="text-end">{{ $row->average_position ? number_format($row->average_position,2,',','.') : '—' }}</td><td class="text-end"><a class="btn btn-sm btn-outline-primary" href="{{ route('admin.analytics.seo.posts.show',$row->post) }}">Detalhes</a></td></tr>@empty<tr><td colspan="7" class="text-center py-4 text-body-secondary">Nenhum artigo encontrado.</td></tr>@endforelse</tbody></table></div></div>
<div class="row g-4">@foreach([['Mais impressões','most_impressions','impressions'],['Melhor CTR','best_ctr','ctr'],['Melhor posição','best_position','average_position'],['Precisam atenção','needs_attention','score']] as [$title,$key,$field])<div class="col-lg-6 col-xxl-3"><div class="card border-0 shadow-sm h-100"><div class="card-header bg-transparent fw-semibold">{{ $title }}</div><div class="list-group list-group-flush">@forelse($rankings[$key] as $row)<a class="list-group-item list-group-item-action d-flex justify-content-between gap-3" href="{{ route('admin.analytics.seo.posts.show',$row->post) }}"><span class="text-truncate">{{ $row->post->title }}</span><strong class="text-nowrap">@if($field==='ctr'){{ number_format($row->$field,2,',','.') }}%@elseif($field==='average_position'){{ number_format($row->$field,2,',','.') }}@elseif($field==='score'){{ $row->$field }}%@else{{ number_format($row->$field,0,',','.') }}@endif</strong></a>@empty<div class="p-3 text-body-secondary">Sem dados.</div>@endforelse</div></div></div>@endforeach</div>
</div>
@endsection
@push('scripts')<script>document.querySelector('[data-period-select]')?.addEventListener('change',function(){document.querySelectorAll('[data-custom-period]').forEach(e=>e.classList.toggle('d-none',this.value!=='custom'));});</script>@endpush
