@extends('layouts.app')
@section('title','Ferramentas | Analytics | Prazzu Tools')
@section('content')
<div class="container-fluid py-4">
<div class="d-flex flex-column flex-xl-row justify-content-between gap-3 mb-4"><div><div class="d-flex gap-2 mb-2"><span class="badge text-bg-primary">Analytics 2.0</span><a class="badge text-bg-light border text-decoration-none" href="{{ route('admin.analytics.index') }}">Dashboard</a></div><h1 class="h2 mb-1">Analytics das Ferramentas</h1><p class="text-body-secondary mb-0">Uso, conclusão, abandono, exportações, histórico e Plus.</p></div>
<form method="get" class="card border-0 shadow-sm"><div class="card-body py-3"><div class="row g-2 align-items-end"><div class="col-auto"><label class="form-label small" for="period">Período</label><select class="form-select" id="period" name="period">@foreach(['today'=>'Hoje','yesterday'=>'Ontem','7'=>'7 dias','30'=>'30 dias','90'=>'90 dias'] as $v=>$l)<option value="{{ $v }}" @selected($selected_period===$v)>{{ $l }}</option>@endforeach</select></div><div class="col-auto"><button class="btn btn-primary" type="submit"><i class="bi bi-funnel me-1"></i>Aplicar</button></div></div></div></form></div>
    @include('admin.analytics.partials.page-guide', ['page' => 'tools'])
<div class="row g-3 mb-4">@foreach([['Ferramentas',$summary['tools'],'bi-grid'],['Aberturas',$summary['opens'],'bi-box-arrow-up-right'],['Inícios',$summary['starts'],'bi-play'],['Conclusões',$summary['completions'],'bi-check-circle'],['Exportações',$summary['exports'],'bi-download'],['Uso Plus',$summary['plus'],'bi-stars']] as [$l,$v,$i])<div class="col-6 col-xl-2"><div class="card border-0 shadow-sm h-100"><div class="card-body"><div class="d-flex justify-content-between"><span class="small text-body-secondary">{{ $l }}</span><i class="bi {{ $i }} text-primary"></i></div><div class="h4 mt-2 mb-0">{{ number_format($v,0,',','.') }}</div></div></div></div>@endforeach</div>
<div class="card border-0 shadow-sm mb-4"><div class="card-header bg-transparent fw-semibold">Desempenho por ferramenta</div><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Ferramenta</th><th class="text-end">Aberturas</th><th class="text-end">Inícios</th><th class="text-end">Conclusões</th><th class="text-end">Conversão</th><th class="text-end">Abandono</th><th class="text-end">Exportações</th></tr></thead><tbody>@forelse($tools as $row)<tr><td><a class="fw-semibold text-decoration-none" href="{{ route('admin.analytics.tools.show',['tool'=>$row->slug,'period'=>$selected_period]) }}">{{ $row->name }}</a><div class="small text-body-secondary">{{ $row->category }}</div></td><td class="text-end">{{ $row->opens }}</td><td class="text-end">{{ $row->starts }}</td><td class="text-end">{{ $row->completions }}</td><td class="text-end"><span class="badge text-bg-success">{{ number_format($row->conversion_rate,1,',','.') }}%</span></td><td class="text-end"><span class="badge text-bg-{{ $row->abandonment_rate > 40 ? 'danger':'secondary' }}">{{ number_format($row->abandonment_rate,1,',','.') }}%</span></td><td class="text-end">{{ $row->exports }}</td></tr>@empty<tr><td colspan="7" class="text-center text-body-secondary py-4">Sem ferramentas.</td></tr>@endforelse</tbody></table></div></div>
<div class="row g-4">@foreach([['Mais abertas',$rankings['most_opened'],'opens'],['Maior conversão',$rankings['highest_conversion'],'conversion_rate'],['Maior abandono',$rankings['highest_abandonment'],'abandonment_rate']] as [$title,$rows,$field])<div class="col-lg-4"><div class="card border-0 shadow-sm h-100"><div class="card-header bg-transparent fw-semibold">{{ $title }}</div><ul class="list-group list-group-flush">@forelse($rows as $row)<li class="list-group-item d-flex justify-content-between"><span>{{ $row->name }}</span><strong>{{ in_array($field,['conversion_rate','abandonment_rate']) ? number_format($row->$field,1,',','.').'%' : $row->$field }}</strong></li>@empty<li class="list-group-item text-body-secondary">Sem dados.</li>@endforelse</ul></div></div>@endforeach</div>
</div>
@endsection
