@extends('layouts.app')
@section('title','Calculadora DIFAL / ICMS Interestadual + FCP')
@section('meta_description','Calcule DIFAL, ICMS interestadual e FCP com alíquota interestadual assistida, base simples ou dupla e memória fiscal.')
@section('content')
<x-tools.page title="Calculadora DIFAL / ICMS Interestadual + FCP" description="Simule o diferencial de alíquotas com premissas fiscais explícitas e memória auditável." icon="bi-receipt-cutoff" slug="calculadora-difal-icms">
<div class="alert alert-info"><strong>Escopo.</strong> Operações interestaduais destinadas a consumidor final. Alíquota interna, FCP, benefícios e método de base dependem da legislação e da mercadoria/serviço e precisam ser confirmados pelo profissional.</div>
<form method="POST" action="{{ route('tools.calculadora-difal-icms.calculate') }}" class="vstack gap-4">@csrf
<x-tools.form-panel title="DIFAL" description="O Essencial resolve o diferencial a partir da base e alíquotas aplicáveis ao caso." badge="Essencial"><div class="row g-3">
<div class="col-md-3"><x-tools.form.input name="competence" label="Competência" type="month" :value="old('competence','2026-07')" required /></div>
<div class="col-md-3"><x-tools.form.money name="base" label="Base/valor tributável" :value="old('base')" required help="Informe a base de cálculo aplicável ao caso." /></div>
@php($ufs=['AC','AL','AP','AM','BA','CE','DF','ES','GO','MA','MT','MS','MG','PA','PB','PR','PE','PI','RJ','RN','RS','RO','RR','SC','SP','SE','TO'])
<div class="col-md-3"><label class="form-label" for="origin_uf">UF origem</label><select class="form-select" name="origin_uf" id="origin_uf" required>@foreach($ufs as $uf)<option value="{{ $uf }}" @selected(old('origin_uf','SP')===$uf)>{{ $uf }}</option>@endforeach</select></div>
<div class="col-md-3"><label class="form-label" for="destination_uf">UF destino</label><select class="form-select" name="destination_uf" id="destination_uf" required>@foreach($ufs as $uf)<option value="{{ $uf }}" @selected(old('destination_uf','MG')===$uf)>{{ $uf }}</option>@endforeach</select></div>
<div class="col-md-3"><x-tools.form.input name="internal_rate" label="Alíquota interna destino (%)" type="number" min="0.000001" max="99.999999" step="0.000001" :value="old('internal_rate','18')" required /></div>
<div class="col-md-3"><x-tools.form.input name="interstate_rate" label="Alíquota interestadual (%)" type="number" min="0" max="100" step="0.000001" :value="old('interstate_rate')" help="Deixe vazio para usar a regra 7%/12%/4% assistida." /></div>
</div></x-tools.form-panel>
<x-tools.form-panel title="Cenário fiscal" description="Recursos Plus ficam liberados durante o lançamento." badge="Prazzu Plus"><div class="row g-3">
<div class="col-md-3"><x-tools.form.input name="fcp_rate" label="FCP (%)" type="number" min="0" max="10" step="0.000001" :value="old('fcp_rate','0')" help="Informe somente se aplicável à mercadoria/operação." /></div>
<div class="col-md-4"><label class="form-label" for="method">Método de base</label><select class="form-select" name="method" id="method"><option value="single_base" @selected(old('method','single_base')==='single_base')>Base única</option><option value="double_base" @selected(old('method')==='double_base')>Base dupla / por dentro</option></select></div>
<div class="col-md-4 form-check mt-4 ms-2"><input class="form-check-input" type="checkbox" name="imported" value="1" id="imported" @checked(old('imported'))><label class="form-check-label" for="imported">Mercadoria enquadrada na alíquota interestadual de 4%</label></div>
<div class="col-md-4 form-check mt-4 ms-2"><input class="form-check-input" type="checkbox" name="recipient_taxpayer" value="1" id="recipient_taxpayer" @checked(old('recipient_taxpayer'))><label class="form-check-label" for="recipient_taxpayer">Destinatário é contribuinte do ICMS</label></div>
</div></x-tools.form-panel>
<div class="form-check"><input class="form-check-input" type="checkbox" name="confirm_rates" value="1" id="confirm_rates" required @checked(old('confirm_rates'))><label class="form-check-label" for="confirm_rates">Confirmo que verifiquei a alíquota interna, FCP, benefícios, NCM/enquadramento e método de base aplicáveis à operação.</label></div>
<div><button class="btn btn-primary btn-lg" type="submit"><i class="bi bi-calculator me-2"></i>Calcular DIFAL</button></div></form>
@isset($result)
@php($money=static fn(int $v)=>\App\Core\Money\Money::fromMinor($v)->formatPtBr())
<div class="mt-5"><x-tools.result-panel title="Resultado" description="Estimativa baseada nas premissas e alíquotas confirmadas."><div class="row g-3 mb-4">@foreach($result->summary as $item)<div class="col-12 col-md-6 col-xl"><x-tools.result-metric :label="$item->label" :value="$item->value" icon="receipt" /></div>@endforeach</div>
@foreach($result->warnings as $warning)<div class="alert alert-warning">{{ $warning->message }}</div>@endforeach
<div class="table-responsive"><table class="table table-sm"><tbody><tr><th>ICMS origem</th><td class="text-end">{{ $money($result->details['origin_icms_minor']) }}</td></tr><tr><th>Base no destino</th><td class="text-end">{{ $money($result->details['destination_base_minor']) }}</td></tr><tr><th>ICMS destino</th><td class="text-end">{{ $money($result->details['destination_icms_minor']) }}</td></tr><tr><th>DIFAL</th><td class="text-end fw-bold">{{ $money($result->details['difal_minor']) }}</td></tr><tr><th>FCP</th><td class="text-end">{{ $money($result->details['fcp_minor']) }}</td></tr><tr class="table-light"><th>Total destino</th><td class="text-end fw-bold">{{ $money($result->details['total_minor']) }}</td></tr></tbody></table></div>
<h3 class="h5 mt-4">Memória fiscal</h3><div class="accordion mb-4" id="difal-memory">@foreach($result->calculationMemory->steps as $step)<div class="accordion-item"><h4 class="accordion-header"><button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#difal-memory-{{ $loop->index }}">{{ $step->label }}</button></h4><div id="difal-memory-{{ $loop->index }}" class="accordion-collapse collapse"><div class="accordion-body"><strong>Fórmula:</strong> {{ $step->formula }}</div></div></div>@endforeach</div>
@if(!empty($historySaved))<div class="alert alert-success">Cálculo salvo no histórico da sua conta.</div>@endif
<div class="d-flex gap-2 flex-wrap"><form method="POST" action="{{ route('tools.calculadora-difal-icms.print') }}" target="_blank">@csrf @foreach($result->details['input'] as $n=>$v)<input type="hidden" name="{{ $n }}" value="{{ is_bool($v)?($v?1:0):$v }}">@endforeach<input type="hidden" name="confirm_rates" value="1"><button class="btn btn-outline-primary">Imprimir / PDF</button></form><form method="POST" action="{{ route('tools.calculadora-difal-icms.export') }}">@csrf @foreach($result->details['input'] as $n=>$v)<input type="hidden" name="{{ $n }}" value="{{ is_bool($v)?($v?1:0):$v }}">@endforeach<input type="hidden" name="confirm_rates" value="1"><button class="btn btn-outline-secondary">Exportar CSV</button></form></div>
</x-tools.result-panel></div>@endisset
</x-tools.page>@endsection
