<?php

declare(strict_types=1);
namespace App\Tools\OvertimeCalculator\Presentation\Controllers;
use App\Core\Access\Services\ToolPersistenceAuthorizer; use App\Core\Dates\ReferenceDate; use App\Core\Export\Data\PrintableDocument; use App\Core\Export\Services\{BrowserPrintExporter,TabularExportService}; use App\Core\Tools\History\Contracts\ToolRunRecorder; use App\Core\Tools\History\Data\{RuleVersion,ToolRunHandle}; use App\Http\Controllers\Controller; use App\Tools\OvertimeCalculator\Application\Data\CalculationInput; use App\Tools\OvertimeCalculator\Domain\Services\Calculator; use App\Tools\OvertimeCalculator\Presentation\Requests\ExecuteToolRequest; use App\Tools\OvertimeCalculator\Tool; use Illuminate\Contracts\View\View; use Illuminate\Http\{Request,Response}; use Symfony\Component\HttpFoundation\StreamedResponse; use Throwable;
final class ToolController extends Controller
{
 public function index(): View { return view('tools-calculadora-hora-extra::index'); }
 public function calculate(ExecuteToolRequest $request, Calculator $calculator, ToolRunRecorder $recorder, ToolPersistenceAuthorizer $persistence, Tool $module): View { $input=$this->input($request->validated()); $run=$this->startRun($request,$recorder,$persistence,$module,$input); try{$result=$calculator->calculate($input); if($run)$recorder->succeed($run,$result->toPersistenceArray());}catch(Throwable $e){if($run)$recorder->fail($run,'overtime.calculation_failed'); throw $e;} $request->flash(); return view('tools-calculadora-hora-extra::index',['result'=>$result,'historySaved'=>$run!==null]); }
 public function printCurrent(ExecuteToolRequest $request, Calculator $calculator, BrowserPrintExporter $print): View { $d=$request->validated(); $r=$calculator->calculate($this->input($d)); return $print->render(new PrintableDocument('Relatório de Hora Extra e Adicional Noturno','tools-calculadora-hora-extra::report',['result'=>$r],'Competência '.$d['competence'],now()->format('d/m/Y H:i'),'Total variável',$r->summary[4]->value)); }
 public function exportCurrent(ExecuteToolRequest $request, Calculator $calculator, TabularExportService $export): Response|StreamedResponse { $r=$calculator->calculate($this->input($request->validated())); return $export->csv('hora-extra-'.now()->format('Y-m-d').'.csv',['Campo','Valor'],array_map(static fn($i)=>[$i->label,$i->value],$r->summary)); }
 private function input(array $d): CalculationInput { return new CalculationInput($d['competence'],$d['base_salary'],(int)$d['monthly_hours'],$d['overtime_50_hours']??'0',$d['overtime_100_hours']??'0',$d['custom_overtime_hours']??'0',(string)($d['custom_premium']??'50'),$d['night_clock_hours']??'0',$d['night_overtime_hours']??'0',(string)($d['night_overtime_premium']??'50'),(int)($d['working_days']??0),(int)($d['rest_days']??0),(bool)($d['include_dsr']??false),(bool)($d['include_reflexes']??false)); }
 private function startRun(Request $request,ToolRunRecorder $recorder,ToolPersistenceAuthorizer $persistence,Tool $module,CalculationInput $input): ?ToolRunHandle { if(!$request->user()||!$persistence->allowsHistory($module,$request->user()))return null; return $recorder->start($module,new RuleVersion('2026.1.0'),ReferenceDate::fromString($input->competence.'-01'),$input->toArray(),$request->user()->id); }
}
