@extends('layouts.app')
@section('title', 'Analytics: '.$post->title.' | Prazzu Tools')
@section('content')
@php($duration=static fn(int $seconds):string=>$seconds>=3600?sprintf('%dh %02dmin',intdiv($seconds,3600),intdiv($seconds%3600,60)):sprintf('%dmin %02ds',intdiv($seconds,60),$seconds%60))
<div class="container-fluid py-4">
<div class="d-flex flex-column flex-lg-row justify-content-between gap-3 mb-4"><div><a class="small text-decoration-none" href="{{ route('admin.blog.analytics') }}"><i class="bi bi-arrow-left me-1"></i>Analytics do blog</a><h1 class="h2 mt-2 mb-1">{{ $post->title }}</h1><p class="text-body-secondary mb-0">{{ $post->category }} · {{ $post->author?->name ?: 'Sem autor' }}</p></div><div class="d-flex gap-2 align-items-start"><a class="btn btn-outline-secondary" target="_blank" href="{{ route('blog.show',$post->slug) }}">Abrir artigo</a><a class="btn btn-outline-primary" href="{{ route('admin.blog.posts.edit',$post) }}">Editar</a></div></div>
<form method="get" class="card border-0 shadow-sm mb-4"><div class="card-body"><div class="row g-2 align-items-end"><div class="col-sm-auto"><label class="form-label small">Período</label><select class="form-select" name="period" data-period-select>@foreach(['today'=>'Hoje','yesterday'=>'Ontem','7'=>'7 dias','30'=>'30 dias','90'=>'90 dias','custom'=>'Personalizado'] as $value=>$label)<option value="{{ $value }}" @selected($selected_period===$value)>{{ $label }}</option>@endforeach</select></div><div class="col-sm-auto {{ $selected_period==='custom'?'':'d-none' }}" data-custom-period><label class="form-label small">De</label><input class="form-control" type="date" name="start" value="{{ request('start',$period->start->toDateString()) }}"></div><div class="col-sm-auto {{ $selected_period==='custom'?'':'d-none' }}" data-custom-period><label class="form-label small">Até</label><input class="form-control" type="date" name="end" value="{{ request('end',$period->end->toDateString()) }}"></div><div class="col-sm-auto"><button class="btn btn-primary">Aplicar</button></div></div></div></form>
<div class="row g-3 mb-4">@foreach([['Views',$metrics->views],['Visitantes',$metrics->unique_visitors],['Sessões',$metrics->sessions],['Tempo médio',$duration($metrics->average_time_seconds)],['Tempo máximo',$duration($metrics->maximum_time_seconds)],['Scroll médio',number_format($metrics->average_scroll,1,',','.').'%'],['Leitura concluída',number_format($metrics->reading_rate,1,',','.').'%'],['Abandono',number_format($metrics->abandonment_rate,1,',','.').'%'],['Compartilhamentos',$metrics->shares],['Downloads',$metrics->downloads],['CTR',number_format($metrics->ctr,1,',','.').'%'],['Assinaturas',$metrics->subscriptions]] as [$label,$value])<div class="col-6 col-lg-3"><div class="card border-0 shadow-sm h-100"><div class="card-body"><div class="small text-body-secondary">{{ $label }}</div><div class="h3 mb-0">{{ is_numeric($value)?number_format($value,0,',','.'):$value }}</div></div></div></div>@endforeach</div>
<div class="row g-4"><div class="col-xl-8"><div class="card border-0 shadow-sm h-100"><div class="card-header bg-transparent fw-semibold">Evolução diária</div><div class="card-body">@php($max=max(1,(int)$daily->max(fn($d)=>max($d->views,$d->visitors,$d->tool_clicks))))<div class="d-flex align-items-end gap-2 overflow-auto" style="min-height:230px">@foreach($daily as $day)<div class="text-center flex-grow-1" style="min-width:46px"><div class="d-flex align-items-end justify-content-center gap-1" style="height:170px"><div class="bg-primary rounded-top" style="height:{{ max(3,round($day->views/$max*160)) }}px;width:28%" title="{{ $day->views }} views"></div><div class="bg-info rounded-top" style="height:{{ max(3,round($day->visitors/$max*160)) }}px;width:28%" title="{{ $day->visitors }} visitantes"></div><div class="bg-success rounded-top" style="height:{{ max(3,round($day->tool_clicks/$max*160)) }}px;width:28%" title="{{ $day->tool_clicks }} cliques"></div></div><small class="text-body-secondary">{{ \Carbon\CarbonImmutable::parse($day->date)->format('d/m') }}</small></div>@endforeach</div></div></div></div><div class="col-xl-4"><div class="card border-0 shadow-sm h-100"><div class="card-header bg-transparent fw-semibold">Ferramentas abertas</div><div class="list-group list-group-flush">@forelse($tools as $tool)<div class="list-group-item d-flex justify-content-between"><code>{{ $tool->tool_slug ?: 'desconhecida' }}</code><strong>{{ $tool->clicks }}</strong></div>@empty<div class="p-3 text-body-secondary">Sem cliques.</div>@endforelse</div></div></div></div>
<div class="card border-0 shadow-sm mt-4"><div class="card-header bg-transparent fw-semibold">Eventos recentes</div><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Evento</th><th>Origem</th><th>Dispositivo</th><th class="text-end">Data</th></tr></thead><tbody>@forelse($recent_events as $event)<tr><td><code>{{ $event->event_name }}</code></td><td>{{ $event->source ?: '—' }}</td><td>{{ $event->device_type ?: '—' }}</td><td class="text-end">{{ $event->occurred_at->format('d/m/Y H:i') }}</td></tr>@empty<tr><td colspan="4" class="text-center py-4 text-body-secondary">Sem eventos.</td></tr>@endforelse</tbody></table></div></div>
</div>
@endsection
@push('scripts')<script>document.querySelector('[data-period-select]')?.addEventListener('change',function(){document.querySelectorAll('[data-custom-period]').forEach(element=>element.classList.toggle('d-none',this.value!=='custom'));});</script>@endpush
