@extends('layouts.app')
@section('title','Calculadora de ISS — Prazzu Tools')
@section('meta_description','Estime ISS por município, serviço, valor e alíquota informada, com retenção, cenários e consolidação.')
@section('content')
<x-tools.page title="Calculadora de ISS" description="Estime o ISS usando a alíquota do município informada por você, sem inferir regras locais automaticamente." icon="building-check" slug="calculadora-iss">
<x-tools.validation-summary />
<form data-testid="tool-form-panel" method="post" action="{{ route('tools.calculadora-iss.calculate') }}" class="d-grid gap-4" data-analytics-form="main">@csrf
<x-tools.form-panel title="Serviço principal" description="Essencial — informe município, serviço, valor e alíquota aplicável ao seu caso."><div class="row g-3">
<div class="col-12 col-md-4"><label class="form-label" for="competence">Competência</label><input class="form-control" id="competence" name="competence" type="month" value="{{ old('competence', now()->format('Y-m')) }}" required></div>
<div class="col-12 col-md-4"><label class="form-label" for="municipality">Município</label><input class="form-control" id="municipality" name="municipality" value="{{ old('municipality','São Paulo/SP') }}" required></div>
<div class="col-12 col-md-4"><label class="form-label" for="service">Serviço</label><input class="form-control" id="service" name="service" value="{{ old('service','Serviço de consultoria') }}" required></div>
<div class="col-12 col-md-6"><label class="form-label" for="value">Valor do serviço</label><div class="input-group"><span class="input-group-text">R$</span><input class="form-control" id="value" name="value" value="{{ old('value','5.000,00') }}" required inputmode="decimal"></div></div>
<div class="col-12 col-md-6"><label class="form-label" for="rate">Alíquota ISS informada</label><div class="input-group"><input class="form-control" id="rate" name="rate" value="{{ old('rate','5') }}" required inputmode="decimal"><span class="input-group-text">%</span></div></div>
</div></x-tools.form-panel>
@if($plusEnabled ?? true)
        <x-tools.form-panel title="Retenção e consolidação" description="Plus — retenção, tomador, serviços adicionais e comparação de alíquotas municipais."><div class="row g-3">
<div class="col-12 col-md-8"><label class="form-label" for="taker">Tomador</label><input class="form-control" id="taker" name="taker" value="{{ old('taker','Cliente principal') }}"></div><div class="col-12 col-md-4 d-flex align-items-end"><div class="form-check mb-2"><input type="hidden" name="retained" value="0"><input class="form-check-input" type="checkbox" id="retained" name="retained" value="1" @checked(old('retained',false))><label class="form-check-label" for="retained">ISS retido pelo tomador</label></div></div>
</div><div class="small text-body-secondary mt-3">Você pode enviar até 10 serviços adicionais e 5 cenários municipais usando os campos estruturados <code>services</code> e <code>municipality_scenarios</code>; o relatório consolida todos os itens.</div></x-tools.form-panel>
        @endif
<div><button class="btn btn-primary" type="submit">Calcular ISS</button></div></form>
@isset($result) @php($money=fn(int $m)=>\App\Core\Money\Money::fromMinor($m)->formatPtBr()) @php($d=$result->details)
<div data-analytics-result="main" data-testid="tool-result" class="mt-5"><x-tools.result-panel title="ISS estimado"><div class="row g-3 mb-4">@foreach($result->summary as $item)<div class="col-12 col-md-6 col-xl-3"><x-tools.result-metric :label="$item->label" :value="$item->value" icon="calculator" /></div>@endforeach</div>@foreach($result->warnings as $warning)<div class="alert alert-light border small">{{ $warning->message }}</div>@endforeach
<h3 class="h5 mt-4">Serviços e tomadores <span class="badge text-bg-primary">Plus</span></h3><div class="table-responsive"><table class="table table-sm"><thead><tr><th>Competência</th><th>Município</th><th>Serviço</th><th>Tomador</th><th class="text-end">Valor</th><th class="text-end">Alíquota</th><th class="text-end">ISS</th><th>Retido</th></tr></thead><tbody>@foreach($d['services'] as $r)<tr><td>{{ $r['competence'] }}</td><td>{{ $r['municipality'] }}</td><td>{{ $r['service'] }}</td><td>{{ $r['taker'] }}</td><td class="text-end">{{ $money($r['value_minor']) }}</td><td class="text-end">{{ $r['rate'] }}%</td><td class="text-end">{{ $money($r['iss_minor']) }}</td><td>{{ $r['retained']?'Sim':'Não' }}</td></tr>@endforeach</tbody></table></div>
<h3 class="h5 mt-4">Consolidação mensal <span class="badge text-bg-primary">Plus</span></h3><div class="row g-3 mb-3"><div class="col-md-4"><x-tools.result-metric label="Valor total" :value="$money($d['totals']['value_minor'])" icon="cash" /></div><div class="col-md-4"><x-tools.result-metric label="ISS total" :value="$money($d['totals']['iss_minor'])" icon="receipt" /></div><div class="col-md-4"><x-tools.result-metric label="ISS retido" :value="$money($d['totals']['retained_minor'])" icon="shield-check" /></div></div><div class="table-responsive"><table class="table table-sm"><thead><tr><th>Competência</th><th>Município</th><th class="text-end">Serviços</th><th class="text-end">Valor</th><th class="text-end">ISS</th><th class="text-end">Retido</th><th class="text-end">A recolher pelo prestador</th></tr></thead><tbody>@foreach($d['monthly_consolidation'] as $r)<tr><td>{{ $r['competence'] }}</td><td>{{ $r['municipality'] }}</td><td class="text-end">{{ $r['services'] }}</td><td class="text-end">{{ $money($r['value_minor']) }}</td><td class="text-end">{{ $money($r['iss_minor']) }}</td><td class="text-end">{{ $money($r['retained_minor']) }}</td><td class="text-end">{{ $money($r['payable_by_provider_minor']) }}</td></tr>@endforeach</tbody></table></div>
@if($d['municipality_scenarios'])<h3 class="h5 mt-4">Cenários por município <span class="badge text-bg-primary">Plus</span></h3><div class="table-responsive"><table class="table table-sm"><thead><tr><th>Município</th><th class="text-end">Alíquota</th><th class="text-end">ISS</th><th class="text-end">Diferença</th></tr></thead><tbody>@foreach($d['municipality_scenarios'] as $r)<tr><td>{{ $r['municipality'] }}</td><td class="text-end">{{ $r['rate'] }}%</td><td class="text-end">{{ $money($r['iss_minor']) }}</td><td class="text-end">{{ $money($r['difference_minor']) }}</td></tr>@endforeach</tbody></table></div>@endif
@php($exportInput=$calculationInput??[])<div class="d-flex gap-2 flex-wrap mt-4" data-testid="download-actions"><a class="btn btn-outline-danger" data-testid="download-pdf" href="{{ route('tools.calculadora-iss.export',array_merge(['format'=>'pdf'],$exportInput)) }}">Exportar PDF</a><a class="btn btn-outline-success" data-testid="download-xlsx" href="{{ route('tools.calculadora-iss.export',array_merge(['format'=>'xlsx'],$exportInput)) }}">Baixar XLSX</a></div></x-tools.result-panel></div>@endisset
</x-tools.page>
@endsection
