<?php

declare(strict_types=1);
namespace App\Tools\SefazFiscalValidator\Domain\Services;
use App\Core\Tools\Calculation\Data\ToolCalculationResult; use App\Core\Tools\Calculation\Data\ToolCalculationSummaryItem; use App\Core\Tools\Calculation\Data\ToolCalculationWarning; use App\Core\Tools\Calculation\Enums\ToolCalculationWarningLevel; use App\Core\Tools\Contracts\ToolCalculationInput; use App\Core\Tools\Contracts\ToolCalculator; use App\Tools\SefazFiscalValidator\Application\Data\CalculationInput; use InvalidArgumentException;
final class Calculator implements ToolCalculator {
 private const UF=['11'=>'RO','12'=>'AC','13'=>'AM','14'=>'RR','15'=>'PA','16'=>'AP','17'=>'TO','21'=>'MA','22'=>'PI','23'=>'CE','24'=>'RN','25'=>'PB','26'=>'PE','27'=>'AL','28'=>'SE','29'=>'BA','31'=>'MG','32'=>'ES','33'=>'RJ','35'=>'SP','41'=>'PR','42'=>'SC','43'=>'RS','50'=>'MS','51'=>'MT','52'=>'GO','53'=>'DF'];
 public function calculate(ToolCalculationInput $input): ToolCalculationResult { if(!$input instanceof CalculationInput) throw new InvalidArgumentException('Entrada inválida.'); $key=strtoupper(preg_replace('/[^A-Z0-9]/i','',$input->accessKey)??''); if(strlen($key)!==44) throw new InvalidArgumentException('A chave deve possuir 44 caracteres.'); $numeric=ctype_digit($key); $uf=self::UF[substr($key,0,2)]??'Código UF não reconhecido'; $aamm=substr($key,2,4); $model=substr($key,20,2); $type=match($model){'55'=>'NF-e','65'=>'NFC-e',default=>'Modelo '.$model}; $series=substr($key,22,3); $number=substr($key,25,9); $emission=substr($key,34,1); $numericCode=substr($key,35,8); $dvStatus='Não verificado para chave alfanumérica'; if($numeric){$dvStatus=$this->validDv($key)?'Dígito verificador consistente':'Dígito verificador inconsistente';} $warnings=[]; if(!in_array($model,['55','65'],true))$warnings[]=new ToolCalculationWarning('model','O modelo indicado não é NF-e 55 nem NFC-e 65.',ToolCalculationWarningLevel::Info); if(!$numeric)$warnings[]=new ToolCalculationWarning('alphanumeric','Chave alfanumérica reconhecida. Esta versão não afirma a validade do DV alfanumérico; a confirmação final depende das especificações vigentes do Portal Nacional.',ToolCalculationWarningLevel::Info); $warnings[]=new ToolCalculationWarning('offline','Diagnóstico offline: não consulta autorização, cancelamento, inutilização, cadastro, protocolo ou disponibilidade dos webservices da SEFAZ.',ToolCalculationWarningLevel::Info); return new ToolCalculationResult('validador-fiscal-sefaz','1.0.0',[new ToolCalculationSummaryItem('document','Documento',$type),new ToolCalculationSummaryItem('uf','UF',$uf),new ToolCalculationSummaryItem('dv','Integridade',$dvStatus)],['access_key'=>$key,'uf'=>$uf,'aamm'=>$aamm,'model'=>$model,'series'=>$series,'number'=>$number,'emission_type'=>$emission,'numeric_code'=>$numericCode,'numeric_legacy'=>$numeric,'official_source'=>'Portal Nacional NF-e — Manual de Orientação do Contribuinte 7.0 e notas técnicas vigentes'], $warnings);}
 private function validDv(string $key): bool { $base=substr($key,0,43); $weight=2; $sum=0; for($i=42;$i>=0;$i--){$sum+=((int)$base[$i])*$weight; $weight=$weight===9?2:$weight+1;} $r=$sum%11; $dv=$r===0||$r===1?0:11-$r; return $dv===(int)$key[43]; }
}
